### ISSUE TITLE
Question: where is Omega_h checked out to when it is on?

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#1002]
I am trying to figure out to what dir is Omega_h supposed to be cloned to relative to the Albany dir when it is enabled.  @cwsmith , @bartgol, can you please let me know?  This is important to try to troubleshoot some clone issues on one of the Sandia nightly testing machines.

**Comment by cwsmith** [comment]
@ikalash It looks like it should be `/path/to/Albany/build/dir/tpls/omegah/Omega_h-prefix/src/Omega_h`.

**Comment by ikalash** [comment]
Ah ok thanks @cwsmith !  I was looking in the tpls/omegah dir and it appeared this was a build/install dir not a clone dir.  I guess I wasn't looking deep enough.  

Is there a way to tell Albany to use an existing Omega_h clone to build Omega_h rather than cloning it?  I'm asking b/c I can't get Omega_h to clone properly with the scripts that are in Albany via the cronjob that runs there.  A workaround would be to have it get cloned separately.

**Comment by bartgol** [comment]
We first call `find_package` to see if there's an available installation. Setting the env var `Omega_h_ROOT` should make `find_package` look there.

**Comment by ikalash** [comment]
Thanks @bartgol .  Does omega_h need to be compiled and installed or you can just point to the source code if it has been cloned?

**Comment by cwsmith** [comment]
The 'external' option currently only supports an existing install (not just the source).
