### ISSUE TITLE
Omega_h failures in warning-free build

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#1009]
It looks like some of the changes to Omega_h are giving rise to warnings which are treated as errors in our warning-free build: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=54093

@cwsmith I think you don't have access to the machine where this is tested and even our CDash site.  Are you OK with me trying to fix the issues and submitting a PR to Omega_h?

**Comment by cwsmith** [comment]
@ikalash Yeah, I don't have access to the dashboard or the nightly test systems.  

Yes! :) We'd welcome the contributions.  Please let me know what I can do to help.  Thank you.

**Comment by ikalash** [comment]
Great!  I submitted a PR for Omega_h: https://github.com/SCOREC/omega_h/pull/73 .  Can you please look at / approve?
