### ISSUE TITLE
Kokkos::vector'is deprecated

### ISSUE THREAD

**Issue by bartgol** [sandialabs/Albany#1019]
I started to see this warning since I upgraded Trilinos:
```
In file included from /home/lbertag/workdir/albany/albany-src/branch/src/evaluators/gather/PHAL_GatherSolution.cpp:9:
/home/lbertag/workdir/albany/albany-src/branch/src/evaluators/gather/PHAL_GatherSolution.hpp:135:24: warning: 'template<class Scalar, class Arg1Type> class Kokkos::vector' is deprecated [-Wdeprecated-declarations]
  135 |     using KV = Kokkos::vector<DynRankView, PHX::Device>;
      |                        ^~~~~~
In file included from /home/lbertag/workdir/albany/albany-src/branch/src/evaluators/gather/PHAL_GatherSolution.hpp:23,
                 from /home/lbertag/workdir/albany/albany-src/branch/src/evaluators/gather/PHAL_GatherSolution.cpp:9:
/storage/workdir/trilinos/trilinos-install/groppello/gcc/opt/develop-serial/include/Kokkos_Vector.hpp:52:25: note: declared here
   52 | class KOKKOS_DEPRECATED vector
```
While I don't expect the class to disappear very soon, we should be proactive, and remove its usage. We don't want to forget and have to rush it when Kokkos finally removes it.

**Comment by jewatkins** [comment]
I don't think we use it very heavily. Only to carry around a vector of device views. Hopefully there's an easy replacement.

**Comment by bartgol** [comment]
I think Kokkos::vector is just a special case of a DualView, so we can probably switch do Kokkos::DualView without too much disruption. And yes, I think we only use it in gather/scatter evaluators.

**Comment by ikalash** [comment]
I guess the errors in the weaver nightlies that started today are unrelated?  

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=54850

```
/.../repos/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp(1319): error: static assertion failed with "Incompatible View copy construction"
```
Does anyone have any insight into this new error?

**Comment by jewatkins** [comment]
yeah that's different. Not sure what happened. I can take a look tomorrow if it happens again.

**Comment by mperego** [comment]
@jewatkins @bartgol @mcarlson801 @kliegeois Anybody willing to take this on?

**Comment by jewatkins** [comment]
is it going to be removed soon from trilinos/kokkos?

**Comment by mperego** [comment]
Not sure, but probably it won't go away until next major release of Kokkos. However, the warning is kind of annoying and it's a good spring cleaning task.

**Comment by jewatkins** [comment]
I'll take a look at this today.
