### ISSUE TITLE
Clean up nightlies to turn off Epetra

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#1037]
Also remove duplicate builds (e.g., if there is a non-Epetra and Epetra build on a machine, the Epetra one should be removed).

**Comment by ikalash** [comment]
Good to know.  I already turned off Epetra in most of the builds.  Speaking of which, do we want to turn off Epetra in the spack nightly as well?  I assume we do.

**Comment by mperego** [comment]
Yes, thanks! We can remove the epetra flag for spack builds as well.

**Comment by ikalash** [comment]
I just checked and the spack build already has Epetra off in Trilinos by default.  Closing.
