### ISSUE TITLE
PyAlbany MatrixOperations test failing in spack nightly

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#1038]
In the Spack nightly with PyAlbany, the MatrixOperations test is failing with the following error: 

```
135/156 Test #135: PyAlbany_MatrixOperations .............................................   Passed    0.83 sec
test 136
        Start 136: PyAlbany_MatrixOperations_MPI

136: Test command: /nightlySpackBuild/spack/opt/spack/linux-rhel8-haswell/gcc-11.1.0/openmpi-4.1.6-knz4yflnjpyldplqsv2ljcm4sxqejcbd/bin/mpiexec "-np" "2" "/nightlySpackBuild/spack/opt/spack/linux-rhel8-haswell/gcc-11.1.0/python-3.9.18-cmndxf3ue5nncpqpdojfnfvvmd5qvmdb/bin/python3.9" "/tmp/ikalash/spack-stage/spack-stage-albany-develop-ycy2yfkfsfl46rpqbsaol4mebadmegnt/spack-build-ycy2yfk/pyAlbany/tests/linearAlgebra/matrixOperations.py"
136: Working Directory: /tmp/ikalash/spack-stage/spack-stage-albany-develop-ycy2yfkfsfl46rpqbsaol4mebadmegnt/spack-build-ycy2yfk/pyAlbany/tests/linearAlgebra
136: Test timeout computed to be: 1200
136: Traceback (most recent call last):
136:   File "/tmp/ikalash/spack-stage/spack-stage-albany-develop-ycy2yfkfsfl46rpqbsaol4mebadmegnt/spack-build-ycy2yfk/pyAlbany/tests/linearAlgebra/matrixOperations.py", line 2, in <module>
136:     import numpy as np
136: ModuleNotFoundError: No module named 'numpy'
136: Traceback (most recent call last):
136:   File "/tmp/ikalash/spack-stage/spack-stage-albany-develop-ycy2yfkfsfl46rpqbsaol4mebadmegnt/spack-build-ycy2yfk/pyAlbany/tests/linearAlgebra/matrixOperations.py", line 2, in <module>
136:     import numpy as np
136: ModuleNotFoundError: No module named 'numpy'
```
The error is surprising b/c there are other PyAlbany tests that use numpy and they are passing.  @kliegeois do you have any insight into this?

**Comment by kliegeois** [comment]
@mperego this is related to the recently added test in your PR is that right ?

**Comment by mperego** [comment]
@kliegeois Yes, but can you help me understand what's wrong? Given that the serial test pass, could it be that numpy doesn't get loaded on other cores?

**Comment by ikalash** [comment]
@mperego , @kliegeois : I will see tonight if the same problem shows up in the PyAlbany nightly w/o spack on camobap.  That build got messed up recently due to @bartgol rearranging the doc dir, but that should be fixed starting today.

**Comment by bartgol** [comment]
Ah, sorry about that. I thought the dashboard subfolder was the only needed one. Thanks for catching that.

**Comment by ikalash** [comment]
@bartgol : no worries.  The dashboards have scripts for building/submitted to the CDash site; this is not done for the Trilinos builds on my machines camobap and mockba, so the scripts were in the nightlyTestHarness directory.

**Comment by ikalash** [comment]
It looks like this is not specific to spack.  It is happening in the nightly builds that turn on PyAlbany on camobap: https://sems-cdash-son.sandia.gov/cdash/test/4326846 , except here it appears the issue is loading PyAlbany.  Is there a missing path, perhaps, to where PyAlbany is supposed to be found?

**Comment by kliegeois** [comment]
@ikalash the fix has been merged.
We should wait for tomorrow results to hopefully close this issue.

**Comment by kliegeois** [comment]
Closing as the test passed https://sems-cdash-son.sandia.gov/cdash/test/4527147 ,

**Comment by ikalash** [comment]
Thanks for fixing this, @kliegeois !  We unfortunately still have failing tests in the spack build, weirdly.  The tests that fail are: 

```
	135 - PyAlbany_MatrixOperations (Failed)
	136 - PyAlbany_MatrixOperations_MPI (Failed)
```
I looked at some of the output.  It looks like the test runs but there is some failure at the end:
```
135:  The Belos solver of type ""Belos::BlockGmresSolMgr": {Flexible: false, Num Blocks: 100, Maximum Iterations: 300, Maximum Restarts: 20, Convergence Tolerance: 1e-10}" returned a solve status of "SOLVE_STATUS_CONVERGED" in 21 iterations with total CPU time of 0.0099856 sec
135: F~PyProblem()
135: ~PyParallelEnv()
135:
135: ======================================================================
135: FAIL: test_all (__main__.TestMatrixOperations)
135: ----------------------------------------------------------------------
135: Traceback (most recent call last):
135:   File "/tmp/ikalash/spack-stage/spack-stage-albany-develop-ycy2yfkfsfl46rpqbsaol4mebadmegnt/spack-build-ycy2yfk/pyAlbany/tests/linearAlgebra/matrixOperations.py", line 98, in test_all
135:     self.assertTrue(err0 < tol0)
135: AssertionError: False is not true
135:
135: ----------------------------------------------------------------------
135: Ran 1 test in 0.137s
```
Do you know what might be happening?  You might need to build the code using spack to reproduce the problem.

**Comment by mperego** [comment]
@ikalash it might be just a tolerance issue. Since you have the spack build already set up, would you mind trying increasing a bit the tolerance tol 0: (e.g. 1e-14) and see if it passes?
https://github.com/sandialabs/Albany/blob/master/pyAlbany/tests/linearAlgebra/matrixOperations.py#L40

**Comment by kliegeois** [comment]
I suspect that the tolerance is too tight here. 

@mperego `tol0 = 1e-15` is a very tight tolerance. Do we need a tolerance that small here?

**Comment by ikalash** [comment]
It works with tol = 1e-13 instead of 1e-15.  Can I change it in the code?

**Comment by ikalash** [comment]
Will do.  I will close this issue again tomorrow if things are clean.

**Comment by mperego** [comment]
Thanks!!

**Comment by kliegeois** [comment]
@ikalash can we close the issue?

**Comment by ikalash** [comment]
Yes!
