### ISSUE TITLE
Can not finish albany spack install since trilinos failed to be installed

### ISSUE THREAD

**Issue by ludydulimi** [sandialabs/Albany#1045]
==> Installing trilinos-master-xa74easea3aklzidtvhratrjmciwfati [33/34]
==> No binary for trilinos-master-xa74easea3aklzidtvhratrjmciwfati found: installing from source
==> No patches needed for trilinos
==> trilinos: Executing phase: 'cmake'
==> trilinos: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

4 errors found in build log:
     177170      492 | #warning "The ThyraEpetraAdapters package is deprecated"
     177171          |  ^~~~~~~
     177172    In file included from /tmp/me/spack-stage/spack-stage-trilin
               os-master-xa74easea3aklzidtvhratrjmciwfati/spack-src/packages/pi
               ro/src/Piro_Epetra_InvertMassMatrixDecorator.cpp:51:
     177173    /tmp/me/spack-stage/spack-stage-trilinos-master-xa74easea3ak
               lzidtvhratrjmciwfati/spack-src/packages/thyra/adapters/epetra/sr
               c/Thyra_EpetraLinearOp.hpp:528:2: warning: #warning "The ThyraEp
               etraAdapters package is deprecated" [-Wcpp]
     177174      528 | #warning "The ThyraEpetraAdapters package is deprecated"
     177175          |  ^~~~~~~
  >> 177176    /tmp/me/spack-stage/spack-stage-trilinos-master-xa74easea3ak
               lzidtvhratrjmciwfati/spack-src/packages/piro/src/Piro_Epetra_Sol
               verFactory.hpp:53:10: fatal error: NOX_Epetra_Observer.H: No suc
               h file or directory
     177177       53 | #include "NOX_Epetra_Observer.H"
     177178          |          ^~~~~~~~~~~~~~~~~~~~~~~
     177179    compilation terminated.
  >> 177180    make[2]: *** [packages/piro/src/CMakeFiles/piro.dir/build.make:1
               49: packages/piro/src/CMakeFiles/piro.dir/Piro_Epetra_SolverFact
               ory.cpp.o] Error 1
     177181    make[2]: *** Waiting for unfinished jobs....
     177182    In file included from /tmp/ne/spack-stage/spack-stage-trilin
               os-master-xa74easea3aklzidtvhratrjmciwfati/spack-src/packages/th
               yra/adapters/epetra/src/Thyra_EpetraThyraWrappers.hpp:46,
     177183                     from /tmp/me/spack-stage/spack-stage-trilin
               os-master-xa74easea3aklzidtvhratrjmciwfati/spack-src/packages/st
               ratimikos/src/Stratimikos_LinearSolverBuilder_decl.hpp:53,
     177184                     from /tmp/me/spack-stage/spack-stage-trilin
               os-master-xa74easea3aklzidtvhratrjmciwfati/spack-build-xa74eas/p
               ackages/stratimikos/adapters/belos/src/../../../src/Stratimikos_
               LinearSolverBuilder.hpp:1,
     177185                     from /tmp/me/spack-stage/spack-stage-trilin
               os-master-xa74easea3aklzidtvhratrjmciwfati/spack-src/packages/st
               ratimikos/src/Stratimikos_DefaultLinearSolverBuilder.hpp:46,
     177186                     from /tmp/me/spack-stage/spack-stage-trilin
               os-master-xa74easea3aklzidtvhratrjmciwfati/spack-src/packages/te
               ko/src/Teko_InverseLibrary.hpp:56,

     ...

     177339      286 | #warning "The Epetra package is deprecated"
     177340          |  ^~~~~~~
     177341    /tmp/me/spack-stage/spack-stage-trilinos-master-xa74easea3ak
               lzidtvhratrjmciwfati/spack-src/packages/thyra/adapters/epetra/sr
               c/Thyra_EpetraLinearOp.hpp:528:2: warning: #warning "The ThyraEp
               etraAdapters package is deprecated" [-Wcpp]
     177342      528 | #warning "The ThyraEpetraAdapters package is deprecated"
     177343          |  ^~~~~~~
     177344    make[2]: Leaving directory '/tmp/me/spack-stage/spack-stage-
               trilinos-master-xa74easea3aklzidtvhratrjmciwfati/spack-build-xa7
               4eas'
  >> 177345    make[1]: *** [CMakeFiles/Makefile2:10489: packages/piro/src/CMak
               eFiles/piro.dir/all] Error 2
     177346    make[1]: Leaving directory '/tmp/me/spack-stage/spack-stage-
               trilinos-master-xa74easea3aklzidtvhratrjmciwfati/spack-build-xa7
               4eas'
  >> 177347    make: *** [Makefile:169: all] Error 2

See build log for details:
  /tmp/me/spack-stage/spack-stage-trilinos-master-xa74easea3aklzidtvhratrjmciwfati/spack-build-out.txt

==> Warning: Skipping build of albany-develop-r436elt3hb4cmlgrvmfxaprnvuk35jmg since trilinos-master-xa74easea3aklzidtvhratrjmciwfati failed
==> Error: albany-develop-r436elt3hb4cmlgrvmfxaprnvuk35jmg: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).

Even I haved installed two trilinos using Spack and cmake. The albany can not be built. What can I do? 
I used Ubuntu 24.04 VM.

**Comment by ikalash** [comment]
Which version of spack are you checking out?  Is it from the main spack repo?  That spack version is not supported for Albany.  A supported version can be found here: https://github.com/E3SM-Project/spack (though I am not 100% sure if this is open-source or if permission needs to be granted - you could have a look and see).

**Comment by ludydulimi** [comment]
I tried to install the E3SM spack again. There is a new problem occurring. 
==>Error: Package 'spack.pkg.builtin.libc' not found.
Use 'spack create' to create a new package.
Did you mean one of the following packages?
libxc
glibc
libxcb
My spack version is 0.22.0.dev0 (f2e410d95ab9c3f9ad28995b9858d77d1d272739).
I used
 $ git clone -c feature.manyFiles=true https://github.com/E3SM-Project/spack/
$ cd spack/bin
$ ./spack install zlibcommands to install it.
My Ubuntu version is 24.04 LTS.
Thank you for your kind reply. It helps me a lot.

**Comment by ikalash** [comment]
I have never seen this error.  It looks like you are trying to install zlib rather than Albany.  To install Albany, I would suggest doing, for example for a gcc-11.1.0 compiler that exists on the machine:

spack --insecure install --dirty --keep-stage albany@develop%gcc@11.1.0

You'd have to edit ~/.spack/linux/compilers.yaml to point to the compiler.

**Comment by ludydulimi** [comment]
Thank you for your help. Everything is okay when I used spack --insecure install --dirty --keep-stage albany@develop%gcc@13.2.0 with edited compilers.yaml.

**Comment by ikalash** [comment]
Great!  Can we close this issue?

**Comment by ludydulimi** [comment]
Of course.
