### ISSUE TITLE
Failing  corePDEs_SideSetLaplacian_3D in CUDA weaver build

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#1056]
It looks like the ```corePDEs_SideSetLaplacian_3D``` test is failing in the Weaver CUDA build.  From the output, there are 0 pivots and NaNs encountered: https://sems-cdash-son.sandia.gov/cdash/test/5416898 .  

@jewatkins @mcarlson801 : could you please have a look?

**Comment by jewatkins** [comment]
that one is new to the gpu tests and I think was never passing, see https://github.com/sandialabs/Albany/issues/1030

**Comment by ikalash** [comment]
Ah ok I see. I will close this then since it is a duplicate.
