### ISSUE TITLE
Failing landIce_FO_MMS_FO tests on some platforms

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#1060]
It looks like the following tests are failing in some of the nighties (camobap and weaver).

landIce_FO_MMS_FO_GLF_QUAD
landIce_FO_MMS_FO_GLF_TRI
landIce_FO_MMS_FO_GLF_TRI_CORNER_CASE
landIce_FO_MMS_FO_GLF_TRI_NONCONST_VELOCITY

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=104669

It looks like comparisons are failing, but the comparison is for a very large value, which seems fishy.

Tagging @mperego and @bartgol since you likely know the most about these.

**Comment by bartgol** [comment]
@mcarlson801 longshot: could this be a similar issue to the one you fixed in some responses a caouple of days ago? I recall that issue had very large diffs in the response/sensitivities.

**Comment by mcarlson801** [comment]
Ah, I didn't see this had an issue opened for it. Yes, these are the tests I mentioned in the other issue that started failing after I fixed an issue with the GLFlux evaluator. I'm going to revert all my changes to this evaluator to see if it fixes and then debug from there.

**Comment by mcarlson801** [comment]
I reverted the uvm-free stuff in ResponseGLFlux and the tests are now passing on my local build on weaver. Looking at the diff, it's not really clear to me what could be causing the issue though. Nightlies should be clean at least while I debug.

**Comment by ikalash** [comment]
Thanks for working on this @mcarlson801 !

**Comment by ikalash** [comment]
These are back to normal, I can confirm.  Should I close this, or keep it open?  It seemed like you might still be investigating the root cause @mcarlson801 .

**Comment by mcarlson801** [comment]
This should be fixed now. If no FO_GIS tests start failing tomorrow, we can close this.

**Comment by mcarlson801** [comment]
These tests are passing now, closing this and moving to the AdjointSensitivity_Thickness issue.
