### ISSUE TITLE
CALI build failure in nightlies

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#1063]
@bartgol : it looks like you might have added a call to ``ComputeWorksetSize`` to the Albany::CISMSTKMesh struct, but it appears the function does not exist.

```
/nightlyCDash/repos/Albany/src/landIce/interfaceWithCISM/Albany_CismSTKMeshStruct.cpp:313:27: error: 'class Albany::CismSTKMeshStruct' has no member named 'computeWorksetSize'
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=106386

**Comment by bartgol** [comment]
Fixed in 814457a5fb72b6e014feb1d0ba08014c441ab271

**Comment by ikalash** [comment]
Thanks @bartgol ! I'll close tomorrow if nightlies are clean.

**Comment by ikalash** [comment]
Thanks for fixing this @bartgol !
