### ISSUE TITLE
Failing nightly builds - Intrepid2 errors

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#1073]
The nightly Albany builds stopped building today due to Intrepid2-related errors:

```
[Albany/src/landIce/utility/Intrepid2_HGRAD_LINE_I4_FEMDef.hpp:152](https://blob/master/Albany/src/landIce/utility/Intrepid2_HGRAD_LINE_I4_FEMDef.hpp#L152):11: error: no member named 'basisCellTopology_' in 'Intrepid2::Basis_HGRAD_LINE_I4_FEM<Kokkos::Serial>'
```
Did the relevant routines in Intrepid2 change, so that we need to port over our code to use them?

**Comment by mperego** [comment]
This is due to https://github.com/trilinos/Trilinos/pull/13411. 
Commit 8ce4331 should fix this.

**Comment by kliegeois** [comment]
I faced the same issue and that commit fixed it for me, thanks @mperego !

**Comment by ikalash** [comment]
Glad to hear that it has been fixed.  I will keep an eye out for the Trilinos PR getting merged in.
