### ISSUE TITLE
Blake debug no warning build failing

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#1090]
The Blake debug no warning build is failing again: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=295181

This seems like something trilinos should monitor? should we turn this into a regular debug build?
@ikalash @mperego @bartgol @mcarlson801

**Comment by mperego** [comment]
pinging @cgcgcg for MueLu issue. 
If it keeps failing it might be good to turn it to a regular debug build. Isn't it possible to suppress only Trilinos warnings?

**Comment by mperego** [comment]
Our no-warning build should probably use the same compilers and setting of warning-free Trilinos PR build.

**Comment by jewatkins** [comment]
> pinging @cgcgcg for MueLu issue. If it keeps failing it might be good to turn it to a regular debug build. Isn't it possible to suppress only Trilinos warnings?

yeah I think we can leave no warning on the albany build but not trilinos.

**Comment by jewatkins** [comment]
oh wait, I think trilinos header files might still get warnings. maybe we can try to match it up with the trilinos settings if someone can point me to them.

**Comment by cgcgcg** [comment]
We'll fix the MueLu issue.

**Comment by cgcgcg** [comment]
@jewatkins Maybe this is helpful for our warnings/errors policy: https://github.com/trilinos/Trilinos/pull/13427

**Comment by jewatkins** [comment]
To me, it looks like these flags are only turned on in cuda builds with a lower gcc: https://github.com/sebrowne/Trilinos/blob/develop/packages/framework/ini-files/config-specs.ini

so maybe it's because we're using a higher gcc (12.2.0) or this is not a cuda build

**Comment by cgcgcg** [comment]
FYI, this should pass on the next iteration.

**Comment by jewatkins** [comment]
thanks!

**Comment by jewatkins** [comment]
To me it looks like "warnings as errors" are only enabled for the cuda builds, is that right? see https://github.com/sebrowne/Trilinos/blob/develop/packages/framework/ini-files/config-specs.ini#L1235
where -Wreorder is on. I'm not sure if the test builds actually enable those flags though. I don't see any cpu builds with "-W...". I'll ask Sam.
