### ISSUE TITLE
Failing FELIX tests on CUDA Kokkos node

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#330]
This issue is a continuation of issue #326. The following FELIX tests are failing:
```
FO_GIS_GisUnstructuredTpetra | Failed | 2m 22s 100ms | Completed (Failed)
FO_GIS_GisAdjointSensitivityTpetra | Failed | 25m  10ms | Completed (Timeout)
FO_GIS_GisSensSMBwrtBetaTpetra | Failed | 25m  10ms | Completed (Timeout)
```
with the following error:
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  cudaFree(m) error( cudaErrorCudartUnloading): driver shutting down /home/projects/albany/build/TrilinosInstall/include/Sacado_DynamicArrayTraits.hpp:233
Traceback functionality not available
```
It turns out, this error is very similar to the errors we were getting in issue #55 with the Epetra tests where we ended up just turning them off in issue #44. I think the issue wasn't with Epetra but with the sensitivities in the Epetra tests. The above tests have sensitivities turned on and that's what's causing the error. I think the issue is that the Fad type for the Tangent is being set to DFad where we would like to use SFad or SLFad for the CUDA tests. I'll see if I can push a fix tomorrow.

**Comment by ikalash** [comment]
Can this issue be closed?
