### ISSUE TITLE
Remove or replace all instances of ALBANY_KOKKOS_UNDER_DEVELOPMENT

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#385]
This has been discussed in #184 and #382. It would be great to remove it and keep the kokkos kernels but there may be some instances where we would like to keep the legacy implementation. At the very least, my suggestion would be to try to remove it everywhere except where kernels are called and make it a requirement to use the Kokkos data abstractions. Then possibly rename it too `ALBANY_USE_KOKKOS_KERNELS` or flip it to `ALBANY_LEGACY_CODE` so that the kokkos kernels are the default.

**Comment by ibaned** [comment]
If we just require Kokkos to be available at compile time, we can make this a runtime instead of a compile-time decision. Like:
```cpp
if (kokkos) {
  Kokkos::parallel_for(...);
} else {
  for (int i ...)
}
```
Note that I'm personally in favor of removing the serial implementations too, but it sounds like the Kokkos ones we're made very readable, which can be improved.

**Comment by bartgol** [comment]
Isn't Kokkos already a requirement for Albany to build? I think we should remove the host implementation whenever the kokkos one is available, and do away with the kokkos macro. Then, little by little, we should do the effort of converting existing ones to a kokkos version.

**Comment by jewatkins** [comment]
Runtime sounds okay to me although it would mean having to bring in a boolean which could be hassle.

I'm pretty certain Kokkos is a requirement. We probably should be a bit careful removing all of the serial implementations as there's no guarantee that the kokkos implementation is better. I think some of the kernels are still lingering from when kokkos was first implemented and may need to be upgraded. I'm mostly thinking about the gather/scatter evaluators which will probably need to be cleaned up again.

**Comment by ikalash** [comment]
To put my 2 cents in: even though it's not good form, I would prefer to keep the legacy non-Kokkos code, as it is much easier to follow and serves as a good example of how to convert for loops to Kokkos parallel fors (I realize that one can get this through the code's git history but that complicates things).  I'm fine with the proposed changing of the ifdef guards.

**Comment by bartgol** [comment]
Ok, I can see how it can be beneficial to keep the non-kokkos version.

@jewatkins your concern about kokkos kernels optimality makes me wonder whether we should run a performance campaign to check their performance against the serial one, and potentially optimize it.

**Comment by jewatkins** [comment]
@bartgol Yeah that would great. I think the only place that may need work is the gather/scatter. I was hoping to tackle that all at once when we refactor all of the finite element assembly (including the Tpetra routines).

**Comment by ikalash** [comment]
@jewatkins : can this be closed?

**Comment by jewatkins** [comment]
Not yet, this is still on my todo list and will most likely be necessary as we further refactor the code.

**Comment by ikalash** [comment]
Ah ok gotcha - just checking.  I was trying to clean up some of the old stale issues we never got around to closing.  I'll keep this one open.

**Comment by jewatkins** [comment]
This was finished with https://github.com/sandialabs/Albany/pull/1029. Thanks @mcarlson801!
