### ISSUE TITLE
Can we remove (full) Stokes and L1L2 evaluators and problems?

### ISSUE THREAD

**Issue by bartgol** [sandialabs/Albany#587]
I don't think we test these problems/evaluators, and I'm not sure whether they would work correctly.

Is it ok to completely remove them? If that's too much, we should at the very least disable them by default, and force the user to manually enable them.

It's not a ton of files, but given even if we can remove 30s of compilation, I'd take it!

@mperego @ikalash

**Comment by mperego** [comment]
I'm fine with removing them. At some point we'll implement a low-order model, but it won't be the l1l2 and it will be likely based on StokesFO problem that now is significantly different from other problems.
@bartgol don't get addicted to cleaning.. haha.

**Comment by ikalash** [comment]
I'm ok with removing these too.  I created those files some 9 years ago, and did not get very far with them, since Albany lacked (lacks) the infrastructure to do vertically integrated models like L1L2.  So I don't think we'd be losing much by removing these even if we plan to implement a low-order model later.

**Comment by bartgol** [comment]
The L1L2 tests are not run, but the full Stokes tests are technically still running. Is there any value in keeping them? I guess not having developed anything in the full Stokes model for a while, it might be quite a bit behind in terms of capabilities...

**Comment by ikalash** [comment]
I see some value in keeping Stokes.  There is linear as well as nonlinear Stokes, including MMS problems.  There is also pressure stabilization to deal with the fact that we don't have mixed elements.  I think these are good examples to have in the code.  And they are tested, as you pointed out.

**Comment by bartgol** [comment]
We already have a Navier Stokes test in the demo PDE library. Is this similar (except for the nonlinear diffusion)? If the overlap is large, then we don't really need this. If it's small, and we want it as an example, maybe it should be moved in the demo PDEs, so we don't build it when developing landice.

**Comment by ikalash** [comment]
Yes, they are similar except the nonlinear diffusion.  IMO, the way the Navier-Stokes problem is structured is somewhat confusing - there are a lot of evaluators and it takes some time to figure out how they work together.  Also there are MMS cases for the nonlinear Stokes coded up which I think can be useful if we ever want to put in full Stokes.  So I guess the question is: are we interested in ever having full Stokes with the nonlinear viscosity in the code?

**Comment by mperego** [comment]
L1L2 is gone. 
Not sure about full Stokes. There is no plan at the moment to use it, but things might change.
We could add an option: -D ENABLE_LANDICE_STOKES  which is off by default, so that we do not need to run the tests all the time.

**Comment by ikalash** [comment]
I'd keep full Stokes.  I have found myself looking at it several times in recent months to refresh my memory on the kinds of stabilizations we used, based on questions I have been asked by other ice sheet modelers.

**Comment by bartgol** [comment]
Can we at least make the compilation of stokes stuff conditional to some cmake var (e.g., LANDICE_ENABLE_LEGACY_CODE)?

**Comment by mperego** [comment]
Yes, that was also what I had in mind.

**Comment by bartgol** [comment]
This was done a long time ago. Closing.
