### ISSUE TITLE
cudaCheckError macro

### ISSUE THREAD

**Issue by bartgol** [sandialabs/Albany#679]
This macro seems to be pointless. See its declaration [here](https://github.com/SNLComputation/Albany/blob/d05fa059e07e40b66b7d3aa1e371fae82170f2f3/src/Albany_Macros.hpp#L14).

@jewatkins @mcarlson801 do you guys hack this line to define it to something meaningfull in nvcc whenever you need to check things on gpu? If you do, we could probably add an `#ifdef KOKKOS_ENABLE_CUDA`, and make this macro clearer. If not, then I'd remove this macro altogether (and its uses).

**Comment by jewatkins** [comment]
I put that macro in along with the push/pop ones a long time ago for debugging before kokkos-tools was a thing. Irina removed part of it by accident here: https://github.com/SNLComputation/Albany/commit/ce03d5ee04b7e73240d3f53bcd52feb01381ed78#diff-e6e93c5a507713ec4df47ca3786b49f5cdda9fa37dbdf47e425ff2807ae5ec7d

I think I was supposed to add it back in but it must have slipped my mind. I think it's safe to remove these as I don't use them anymore. I can always add them back in if needed.
