### ISSUE TITLE
PyAlbany extreme event tests failing

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#744]
I noticed that the PyAlbany extreme event tests have started failing: 

```
F~PyProblem()
~PyParallelEnv()

======================================================================
FAIL: test_all (__main__.TestExtremeEvent)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nightlyCDash/build/IKTAlbanyFPECheckDbg/PyAlbany/tests/small/extremeEvent/thermal_steady.py", line 85, in test_all
    self.assertTrue(np.amax(np.abs(expected_F_star - F_star)) < tol)
AssertionError: False is not true
```

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=23165

I believe the test is new and has been failing since it was created.  I assume @kliegeois this is your test?

**Comment by kliegeois** [comment]
Yes, it is my test @ikalash. It is strange that it is behaving like that.
I am curious to know what the computed `F_star` values are and if they are very different from the expected ones.

Would it be fine if I add a commit that print the computes values? This will obviously not resolve the issue for the next nightly test but this will help to understand the issue and whether the tolerance is too thigh for instance.
I am proposing this as I have not faced this issue for now.

**Comment by ikalash** [comment]
@kliegeois : sorry for the delay in my response.  Yes, please add a commit that prints the values, in case that helps with the debugging.

**Comment by kliegeois** [comment]
It should be resolved now. Let's wait for tomorrow results.

**Comment by ikalash** [comment]
Thanks @kliegeois !  I'll check the nightlies today and close the issue if things are good.

**Comment by ikalash** [comment]
I can confirm that this issue is resolved.  Thanks @kliegeois !

**Comment by kliegeois** [comment]
@ikalash perfect! Thanks!
