### ISSUE TITLE
Configure error due to missing ALI yaml file

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#750]
It looks like there's a missing yaml file causing a broken build on cee-compute020:

```
CMake Error: File /projects/albany/nightlyAlbanyCDash/repos/Albany/tests/small/LandIce/FO_GIS/input_fo_gis_adjoint_sensitivity_bed_and_topT.yaml does not exist.
CMake Error at tests/small/LandIce/FO_GIS/CMakeLists.txt:366 (configure_file):
  configure_file Problem configuring file
```
https://sems-cdash-son.sandia.gov/cdash/viewConfigure.php?buildid=23633

@mperego I'm guessing this got broken yesterday w/ your PR getting merged in?

**Comment by mperego** [comment]
Argh! Sorry, I  committed and pushed the missing file.
