### ISSUE TITLE
pyAlbany build error

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#765]
Looks like there are issues with some of the newly defined macros:

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=26035

```
os << R"(** Trilinos git commit id - )" << ALBANY_TRILINOS_GIT_COMMIT_ID << std::endl;
```
```
   os << R"(** Albany git branch ------ )" << ALBANY_GIT_BRANCH << std::endl;
                                                ^~~~~~~~~~~~~~~~~
                                                ALBANY_TRACE
```
@bartgol , @kliegeois : could one of you please have a look / fix this?

**Comment by bartgol** [comment]
Ah, my bad, I did not fix PyAlbany. I'll push a quick fix now.

**Comment by bartgol** [comment]
0236196 should fix the error.

**Comment by kliegeois** [comment]
Thanks @bartgol !

**Comment by ikalash** [comment]
Thanks @bartgol  - I'll close this issue tomorrow provided the CDash is clean.

**Comment by ikalash** [comment]
It looks like now the PyAlbany tests are failing: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=26080

It says: 
```
Traceback (most recent call last):
  File "/nightlyCDash/build/IKTAlbanyFPECheckDbg/PyAlbany/tests/small/extremeEvent/thermal_steady.py", line 7, in <module>
    from PyAlbany import Utils
ModuleNotFoundError: No module named 'PyAlbany'
```
Or would this be a configuration issue on the machine the test is run?  It appears these tests are new and never ran correctly on the test machine in the past.

**Comment by kliegeois** [comment]
@ikalash I think that the issue now is that scipy is not installed on the test machine. It seems that only the extreme event tests (which do require scipy) are failing.

**Comment by ikalash** [comment]
Ah yes, I see.  I think what happened is somehow my python package installs went away when I upgraded my workstation a week and a half ago.  I've reinstalled scipy and the tests pass.

**Comment by kliegeois** [comment]
The tests fail again:

```
Traceback (most recent call last):
  File "/nightlyCDash/build/IKTAlbanyFPECheckDbg/PyAlbany/tests/small/ExtremeEvent/thermal_steady_hessian.py", line 11, in <module>
    import ExtremeEvent as ee   
  File "/nightlyCDash/build/IKTAlbanyFPECheckDbg/PyAlbany/tests/small/ExtremeEvent/ExtremeEvent.py", line 6, in <module>
    from PyAlbany import Distributions as dist
ModuleNotFoundError: No module named 'PyAlbany'
Traceback (most recent call last):
  File "/nightlyCDash/build/IKTAlbanyFPECheckDbg/PyAlbany/tests/small/ExtremeEvent/thermal_steady_hessian.py", line 7, in <module>
    from PyAlbany import Utils
ModuleNotFoundError: No module named 'PyAlbany'
```

I am not able to reproduce the error on my machine. The issue might be related to the lines from Distributions.py:
```
from scipy.special import erfinv
import scipy.stats
```

@ikalash could you check if those lines throw an error when doing the following?

```
 ~ % python
Python 3.8.8 (default, Apr 13 2021, 12:59:45)
[Clang 10.0.0 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy.special import erfinv
>>> import scipy.stats
>>>
```

**Comment by ikalash** [comment]
@kliegeois : I just checked and there is no error

```
[ikalash@camobap ~]$ python
Python 3.10.0 (default, Oct  4 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy.special import erfinv
>>> import scipy.stats
```
We may want to hold off on trouble shooting this further, however, as the workstation where this happens will be reformatted tomorrow to have RHEL8 instead of Fedora.  After 7 or so years of fighting the battle that allowed me to maintain a non-COE OS, I have been forced to surrender...  we can see if this problem persists with the new OS, after I've had the chance to get everything reset up with it.

**Comment by ikalash** [comment]
I'm still getting this issue after the OS change on camobap.

**Comment by kliegeois** [comment]
I am back at work; I will look into that.

BTW, Happy New year!

**Comment by kliegeois** [comment]
It seems that it can be closed! Thanks @ikalash !

**Comment by ikalash** [comment]
Indeed.  Thanks for your help @kliegeois !
