### ISSUE TITLE
Performance regression on blake

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#767]
I noticed a performance regression on blake that seems to be pretty significant (somewhere around 20% slowdown depending on the case). Unfortunately, I don't have a lot of data because the performance tests were down during that period but it happened between Oct. 26th and Nov. 6th and it seems to be related to the boundary conditions and the assembly:
Oct. 26th Run:
```
** Trilinos git commit id - 3bae707
** Albany git commit id --- 323a90b
|   |   |   |   Albany: Total Fill Time: 12.6747 - 99.895% [201] {min=12.5964, max=12.7485, std dev=0.0354548}
|   |   |   |   |   |   |   Phalanx: Evaluator 86: [<Jacobian>] StokesFOLateralResid<Jacobian>: 0.0241899 - 0.249467% [100] {min=0.000457268, max=0.177912, std dev=0.0314022}
|   |   |   |   |   |   |   Phalanx: Evaluator 87: [<Jacobian>] StokesFOBasalResid<Jacobian>: 0.0732972 - 0.755904% [100] {min=0.0612907, max=0.104363, std dev=0.00537095}
|   |   |   |   |   |   |   Phalanx: Evaluator 68: [<Jacobian>] Scatter Velocity Residual<Jacobian>: 2.58533 - 26.6621% [100] {min=2.46749, max=2.75813, std dev=0.0644871}
|   |   |   |   |   |   Albany Jacobian Fill: Export: 0.81807 - 7.53388% [100] {min=0.486474, max=1.10587, std dev=0.144271}
```
Nov. 6th Run:
```
** Trilinos git commit id - e15cf42
** Albany git commit id --- e14f44a
|   |   |   |   Albany: Total Fill Time: 15.1982 - 99.909% [201] {min=15.082, max=15.3161, std dev=0.0476297}
|   |   |   |   |   |   |   Phalanx: Evaluator 86: [<Jacobian>] StokesFOLateralResid<Jacobian>: 0.147669 - 1.31135% [100] {min=0.000441569, max=1.17069, std dev=0.203318}
|   |   |   |   |   |   |   Phalanx: Evaluator 87: [<Jacobian>] StokesFOBasalResid<Jacobian>: 0.116388 - 1.03357% [100] {min=0.103936, max=0.128278, std dev=0.00484907}
|   |   |   |   |   |   |   Phalanx: Evaluator 68: [<Jacobian>] Scatter Velocity Residual<Jacobian>: 3.95909 - 35.1579% [100] {min=3.7384, max=4.11777, std dev=0.0938339}
|   |   |   |   |   |   Albany Jacobian Fill: Export: 1.47505 - 11.272% [100] {min=0.553215, max=2.04266, std dev=0.258961}
```
There was also a regression in the residual. This doesn't seem to show up in the GPU tests, it seems to be CPU-only. I don't see anything significant in the history other than the STK deprecation changes.

@mperego @bartgol Any ideas? Was there something to the STK changes that would cause this? We may just have to let this one slide because I don't see anything obvious...

**Comment by bartgol** [comment]
For the LateralResid ev, it seems it might just be a worse distribution (max and min are roughly the same, but std dev increased). I don't think we did anything that could have deteriorated the balancing though.

I have no ideas regarding the other two. The residual scatter might have something to do with Tpetra maybe? I guess our logs don't show Tpetra timers, so we can't tell But the fact that the Export time also went up kind of makes me thing that. Another possibility is that blake is in need of a reboot (sometimes that proved to be a cause of slowdown), though I _think_ it got rebooted not long ago...

**Comment by jewatkins** [comment]
Hmm I think one thing that all these have in common is that they all have a Kokkos atomic and there was a Kokkos promotion to 3.5.00 during that time:
https://github.com/trilinos/Trilinos/commit/91e55fa9a3861042fb3f07fc63bb9129289129f4
Maybe there's something there.

**Comment by bartgol** [comment]
IIRC, there should be a Kokkos briefing seminar next week, and the atomic thing was on the menu. Perhaps we should plan to have one of us attending.

**Comment by jewatkins** [comment]
> IIRC, there should be a Kokkos briefing seminar next week, and the atomic thing was on the menu. Perhaps we should plan to have one of us attending.

Could you forward the invite?

**Comment by jewatkins** [comment]
I'll try testing a build without the atomic and see what happens. If that's the issue, I'll create a wrapper for it for serial builds.

**Comment by jewatkins** [comment]
Okay, that was indeed the issue. There must be some overhead cost (or less compiler optimizations) with the new kokkos atomic. Maybe if I update the compiler, this issue will go away? Either way, it's probably best to just wrap the atomic ops so that we don't use it for serial builds.
