### ISSUE TITLE
Nightly tests failing due to "Random Parameters"

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#768]
@kliegeois @mperego @bartgol 
It looks like the tests are failing due to a recent PR https://github.com/sandialabs/Albany/pull/766.

Was the intention to make "Random Parameters" a requirement in the LandIce StokesFO problem? If not, then the sublist needs to be checked for existence otherwise it will get created.

**Comment by jewatkins** [comment]
Failure example:
```
p=1: *** Caught standard std::exception of type 'Teuchos::Exceptions::InvalidParameterName' :

 Error!  The parameter "Number Of Parameters" does not exist
 in the parameter (sub)list "Albany Parameters->Problem->Random Parameters".
 
 The current parameters set in (sub)list "Albany Parameters->Problem->Random Parameters" are:
 
   {
   }
 
 
 Throw number = 1
```

**Comment by kliegeois** [comment]
Thanks @mperego !
