### ISSUE TITLE
Blake warnings as error build broken

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#773]
The blake warnings as errors build got broken with the PR merged in yesterday: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=26939

I started trying to fix the unused variables, but there are other errors having to do with -Werror=reorder.  @bartgol can you please fix those?

**Comment by bartgol** [comment]
88e8ce6dc should fix a couple of warnings, but what I see at the page you linked is weird. I don't have the same things at the locations pointed by the compiler. More thoughts:

- start/nunk error: I don't see why they'd be unused. Unless static fads trigger some code to be compiled away?
- there are errors of the form "no rule to make target X needed by Y": I usually get those when the bld dir is not clean. Does the nightly run in a clean folder?

**Comment by ikalash** [comment]
@bartgol : so I fixed some of the errors already - this is why the line numbers did not match.  Now there are new errors.  I think one will have to build the code to see what they are in order to fix them...  maybe I will try to do this later today using the nightly build if I have time.  I started but then it was looking involved and I had to go to some meetings, so I opened the issue.
