### ISSUE TITLE
PARALLEL_EXODUS_SUPPORTED directive appears to not work all the time

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#774]
It looks like the PARALLEL_EXODUS_SUPPORTED directive is not always working as expected.  On one of my machines, the Ioss test are failing due to not having a parallel netcdf, even though they are ifdef'ed against this:

https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=27043

@mperego  - I think you are the one who put the ifdef guards in.  Can you please have a look when you get the chance?

**Comment by bartgol** [comment]
The configure log shows
```
-- Performing Test PARALLEL_EXODUS_SUPPORTED
-- Performing Test PARALLEL_EXODUS_SUPPORTED - Success
```
The check for parallel support is done by trying to compile
```
#include <exodusII_par.h>
int main()
{
  return 0;
}
```
Which can compile provided that `NC_HAS_PARALLEL` is defined. However, inside `ex_open_par.h`, exodus checks that `NC_HAS_PNETCDF` is defined. `NC_HAS_PARALLEL` is on if netcdf has "parallel IO support via HDF5 and/or PnetCDF" (greeping NC_HAS_PARLLEL inside netcdf source folder).

As the netcdf source folder says, I always considered parallel support enabled if either PnetCDF is present _OR_ if HDF5 has parallel support enabled. However, Trilinos seems to do two different things in `exodusII.h` and in `ex_open_par.h`. I will open an issue in trilinos, to clarify it.

**Comment by mperego** [comment]
@ikalash I can reproduce this, and I don't understand why the FO tests work fine (when Use Serial Mesh is set to true, as in your case) whereas this IOSS test fails. @bartgol any clue?

**Comment by bartgol** [comment]
I had a quick discussion with SEACAS folks on the trilinos github page, and it helped to clarify things.

So, I think some of our files (like quadQuad.exo in the test linked at the top) are not in netCDF-4 and not in HDF5 format, that is, classic netCDF files. For these files, we _need_ PnetCDF in order to open the file in parallel.

See #trilinos/trilinos10059 for more details.

I see two options:
 1. we add also a check for PnetCDF to determine if parallel exodus is supported (on top of the current check for exodusII_par.h to compile).
 2. we change our exodus files to be in CDF4 or HDF5 format.
 
 Option 1 is probably the easiest, but might preclude parallel tests on some platforms.

**Comment by mperego** [comment]
thanks @bartgol! It seems that there are really few tests that fails, so are those the only files that are not in CDF4 or HDF5 format? How could we convert them?

**Comment by mperego** [comment]
I guess I could easily use `AsciiSTKMaes2D` to re-create those 2d meshes in the right format.

**Comment by bartgol** [comment]
I am not sure. I have no idea where those files were generated. I tried to run decomp+conjoin, but that only turned the file type from 1 to 2 (in exodus codes, those are "classsic netcdf" and "64-bit offset netcdf"), which are both handled with the pnetcdf reader.

I did
```
$ decomp -processors 2 quadQuad.exo
$ conjoin quadQuad.exo.2.0 quadQuad.exo.2.1
$ xxd -b quadQuad.exo | head -n 1
00000000: 01000011 01000100 01000110 00000001 00000000 00000000  CDF...
$ xxd -b conjoin-out.e | head -n 1
00000000: 01000011 01000100 01000110 00000010 00000000 00000000  CDF...
```
The xxd command shows the content in binary form. The first 3 entries are just the string CDF, the next number is the "file type" (1=netcdf, 2=64-bit netcdf, 4=pnetcdf cdf5, 5=hdf5 file). 1 and 2 need pnetcdf, 4 needs NC_HAS_CDF5, and 5 needs NC_HAS_HDF5.

**Comment by mperego** [comment]
OK, let me try the `AsciiSTKMesh2D` path, unless you think it's best to check that exodus is built with PNetcdf

**Comment by bartgol** [comment]
I mean, how many times is this going to happen again, for other files? Besides, I just did a check on mappy: I have pnetcdf built in trilinos, so the test works for me, but the output exo files generated by the test (quadOut_tpetra.4.[0-3]) are still of type 2 (64-bit offset). That means that our output files are not readable in parallel (unless already partitioned). Perhaps there is some option we need to set, when creating exo files, to guarantee that we use CDF5 or HDF5 format.

**Comment by mperego** [comment]
How do you check the type of the exo files?

**Comment by bartgol** [comment]
```
xxd -b filename.exo | head -n 1
```
CDF file output:
```
00000000: 01000011 01000100 01000110 00000001 00000000 00000000  CDF...
```
HDF file output:
```
00000000: 10001001 01001000 01000100 01000110 00001101 00001010  .HDF..
```
The latter means HDF5 format. The former can be classic netcdf (1), 64-bit netcdf (2), or netcdf CDF5 (4), depending on the number at the 4th place in the row (00000001, in this case)

**Comment by ikalash** [comment]
It looks like this issue has resolved itself / been resolved - closing.
