### ISSUE TITLE
Blake warning-free build broken

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#781]
It looks like the blake warning-free build got broken recently: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=28500 .  Could someone please have a look?  Seems it has to do with ROL tests.  Maybe we can just turn them off?

@mperego

**Comment by mperego** [comment]
@ikalash we talked about that at the last Albany meeting. ROL has to fix this in a few weeks. It's up to you, if you prefer you can disable ROL tests or just wait until it gets fixed in ROL.

**Comment by ikalash** [comment]
Yes I remember, I just didn't want to forget about this, so I opened the issue.  I think I'll just disable the tests, if there are no objections.

**Comment by mperego** [comment]
Actually, why don't we simply remove the Tpetra and Xpetra Deprecated code lines?

**Comment by ikalash** [comment]
Yes I can do that.

**Comment by mperego** [comment]
Thanks!
