### ISSUE TITLE
TriKota in Albany?

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#783]
I received an email today from @ccober6 discussing plans to deprecate TriKota and asking if we are using it.  We have not used it in years and I am not aware of any plans to use it in the future - @kliegeois , @mperego , @bartgol : can you please confirm?

**Comment by kliegeois** [comment]
I am not using it and I have no plan to do so.

**Comment by mperego** [comment]
Yes. Even if in the future we wanted to use Dakota, we won't probably due it through Trikota.

**Comment by bartgol** [comment]
I've never used it.
