### ISSUE TITLE
Errors when make install

### ISSUE THREAD

**Issue by kliegeois** [sandialabs/Albany#792]
@bartgol since you have removed some files in #791, the CMakeLists.txt should have been updated accordingly to remove the deleted files.

**Comment by bartgol** [comment]
ah, my bad. fix coming

**Comment by kliegeois** [comment]
Thanks! I was going to fix it but I have connection issue.

**Comment by ikalash** [comment]
Was this the same error as this: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=29302 ?

**Comment by bartgol** [comment]
Nope, that's a build error. Another fix coming. :)

**Comment by bartgol** [comment]
CISM driver fixed in cb5ee8370

**Comment by ikalash** [comment]
Ok.  Could you please open an issue on these problems?

**Comment by bartgol** [comment]
Well, this was the issue, but it got fixed.
