### ISSUE TITLE
Performance tests broken due to Kokkos changes

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#804]
It looks like the same configuration error we had yesterday in Albany is present now in the performance tests: https://sems-cdash-son.sandia.gov/cdash/build/32806/configure.  I think a similar change to this one needs to be made to fix the problem: https://github.com/sandialabs/Albany/pull/803 .  @jewatkins could you please do this?

**Comment by jewatkins** [comment]
Yes, I pushed a fix this morning: https://github.com/sandialabs/ali-perf-tests/commit/71a6cfe8845040bca49e4a64b401809be9ecd257. It worked when I tested it so it should work tonight.

**Comment by ikalash** [comment]
Great!  Sorry, I've been in meetings all morning and am just now trying to get caught up.  Will close tomorrow if the build is clean.
