### ISSUE TITLE
PyAlbany compilation error

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#806]
It looks like PyAlbany failed to compile last night due to a missing include:

```
/nightlyCDash/repos/Albany/PyAlbany/src/PyAlbany_Stokhos.hpp:10:10: fatal error: Stokhos_KL_ExponentialRandomField.hpp: No such file or directory
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=33107

My guess is the file included either got removed or renamed in Trilinos.  Do we really need the include?  Would be great if you could have a look @kliegeois .

**Comment by kliegeois** [comment]
I will look at this.

**Comment by kliegeois** [comment]
The file is still there.
We need it for that function so I guess that I should guard that file/function with some macro that check if the used Trilinos build supports/enables Stokhos.

**Comment by ikalash** [comment]
Ah ok.  Could you please add the macro in this case?
