### ISSUE TITLE
Broken blake warnings-as-errors build

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#809]
It looks like recent changes to Albany broke the warnings-as-errors build on Blake: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=33769.  Could someone please have a look?  @mperego

**Comment by mperego** [comment]
@ikalash thanks. I'll take care of it.

**Comment by ikalash** [comment]
Thanks @mperego !

**Comment by ikalash** [comment]
Looks like this is fixed - thanks @mperego !
