### ISSUE TITLE
Failing Albany build on Cori due to missing Stratimikos header

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#813]
The Cori nightly build failed last night due to a missing Stratimimkos header: https://my.cdash.org/viewBuildError.php?buildid=2175679 . 

```
[TrilinosInstall/include/Stratimikos_DefaultLinearSolverBuilder.hpp:46](https://github.com/gahansen/Albany/blob/master/TrilinosInstall/include/Stratimikos_DefaultLinearSolverBuilder.hpp#L46):10: fatal error: Stratimikos_LinearSolverBuilder.hpp: No such file or directory
 #include "Stratimikos_LinearSolverBuilder.hpp"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
I'm guessing the file got removed/renamed in Trilinos.  Could someone please look at this and fix the issue?  I'm on foreign travel.  I am guessing this will show up in the other nightlies, but I don't have access from abroad to that CDash site.

@mperego, @jewatkins .

**Comment by jewatkins** [comment]
Yeah the other builds are failing too. I'll take a look.

**Comment by mperego** [comment]
I guess this is related to https://github.com/trilinos/Trilinos/commit/e08b53677de4ac72b9e060001dd5e63b6c2b167f
@cgcgcg

**Comment by mperego** [comment]
https://github.com/trilinos/Trilinos/pull/10507

**Comment by jewatkins** [comment]
Right, this PR will fix it once its pushed: https://github.com/trilinos/Trilinos/pull/10605

**Comment by ikalash** [comment]
Seems this has been resolved at least judging from the Cori job - closing.
