### ISSUE TITLE
Failing nightly build with PyTrilinos

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#818]
The nightly build with PyTrilinos is failing with the following error: 
```
3151/3205] Swig source /nightlyAlbanyTests/Results/Trilinos/packages/PyTrilinos/src/Tpetra.i
FAILED: packages/PyTrilinos/src/TpetraPYTHON_wrap.cpp packages/PyTrilinos/src/PyTrilinos/Tpetra.py
/bin/sh packages/PyTrilinos/src/CMakeFiles/TpetraPYTHON_wrap.cpp-7f95a32.sh d4eecafc3b8126ec
/nightlyAlbanyTests/Results/Trilinos/packages/PyTrilinos/src/Tpetra.i:634: Error: Unable to find 'TpetraClassic_config.h'
[3152/3205] Linking CXX shared module packages/PyTrilinos/src/PyTrilinos/_IFPACK.so
```
@kliegeois , have you encountered this?

**Comment by kliegeois** [comment]
No but this error will be gone with the merge of #816.

**Comment by ikalash** [comment]
Ok great.

**Comment by mperego** [comment]
@ikalash as a consequence of #816, we will need to modify this build. PyTrilinos and swig are no longer needed but pybind is required instead. I think it make sense to turn off this build off until #816 is merged and the build is updated.

**Comment by ikalash** [comment]
What's the timeline for merging in the PR?  I think I will keep the build but just turn off PyAlbany in it.  It is one of the few Debug builds of ALbany.

**Comment by mperego** [comment]
That's a good idea. I think it could be merge early next week, if @kliegeois has time to work on it.

**Comment by kliegeois** [comment]
The timeline will mostly depend on the review(s). I can resolve Mauro's comments today but I don't know if there will be any other reviews.

**Comment by mperego** [comment]
Great! It's probably good if @mcarlson801 tries it out, since he is the one that has been using PyAlbany recently, besides Kim.

**Comment by mcarlson801** [comment]
Looks like I missed the ping requesting a review for me, my bad. I'll take a look and try it out asap.

**Comment by kliegeois** [comment]
@ikalash Can we close this issue or do you prefer to wait for the next nightly build to pass?

**Comment by ikalash** [comment]
We can close.  The nightlies were good yesterday with the changes.
