### ISSUE TITLE
Broken PyAlbany build

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#823]
The PyAlbany build on camobap started failing a few days ago due to a pybind11 version problem:

```
CMake Error at PyAlbany/CMakeLists.txt:86 (MESSAGE):
  PYBIND11_VERSION_ERROR is defined; the python executable cannot access
  pybind11.
```
https://sems-cdash-son.sandia.gov/cdash/build/36965/configure

@kliegeois , I am guessing this is due to the recent changes in your PR?  Do I need to make some changes to the Albany configuration?

**Comment by kliegeois** [comment]
Yes, it is related to my PR. It means that pybind11 was not found by the used python.
What is the camobap machine? Can you connect to it and reproduce the issue?
It looks like a PYTHONPATH issue or that pybind11 was not installed.
Was PyAlbany working on that machine before?

**Comment by ikalash** [comment]
The machine has pybind11 installed.  Yes, the build was working until Wednesday.  What should PYTHONPATH be?  When I echo it, it is empty.  I am not sure what you would like me to reproduce - the output will be the same as the output linked above that shows up in the nightly.

**Comment by kliegeois** [comment]
Could you try this?

```
/usr/bin/python3 -c "import pybind11; print(pybind11.__version__)"
```

**Comment by ikalash** [comment]
It's not found. 

```
[ikalash@camobap Albany]$ /usr/bin/python3 -c "import pybind11; print(pybind11.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pybind11'

```
It's weird b/c if I try to install pybind11, it says it's already installed:
```
[ikalash@camobap Albany]$ !1090
sudo pip3 install pybind11
[sudo] password for ikalash: 
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
Requirement already satisfied: pybind11 in /root/.local/lib/python3.6/site-packages
```
And also I know it's there b/c the build worked before.

**Comment by kliegeois** [comment]
Can you try to add `/root/.local/lib/python3.6/site-packages` to your PYTHONPATH and retry?

**Comment by ikalash** [comment]
FWIW, I changed the blake warning free build to enable Albany and am getting the same error as on camobap: https://sems-cdash-son.sandia.gov/cdash/build/37028/configure .

**Comment by kliegeois** [comment]
@ikalash I disabled the check that throws the error on those 2 builds.

**Comment by kliegeois** [comment]
@ikalash yes. I think that the cmake check that I introduced is too strict; I think that it is a sufficient but not necessary requirement.

**Comment by kliegeois** [comment]
It seems that it passed on camobap but it failed on [blake-serial-Albany-gcc-no-warn](https://sems-cdash-son.sandia.gov/cdash/build/37122):

```
-- Check required dependencies:
CMake Error at PyAlbany/CMakeLists.txt:100 (MESSAGE):
  Mpi4Py_VERSION_ERROR is defined; the python executable cannot access
  mpi4py.
```

This means that `${PYTHON_EXECUTABLE} -c "import mpi4py; print(mpi4py.__version__)"` failed.
Is mpi4py installed and accessible?

**Comment by bartgol** [comment]
We can pip install it locally (in the home of whomever is the user launching the testing, I'm guessing Irina?).

**Comment by kliegeois** [comment]
@bartgol yes, that's what should be done but it is strange that it actually worked before.

**Comment by ikalash** [comment]
@jewatkins owns the nightlies on blake now not me. I am guessing he will need to install mpi4py locally:

```
env MPICC=$MY_MPI_COMPILER pip3 install --no-cache-dir mpi4py --trusted-host=pypi.org --trusted-host=files.pythonhosted.org --user
```
Could you please do this Jerry when you are back?

**Comment by jewatkins** [comment]
Done. But will probably have to wait until tomorrow to see if it works.

**Comment by ikalash** [comment]
Thanks, Jerry!  No problem, I'll monitor this for the next couple of days.

**Comment by kliegeois** [comment]
It seems that it worked, thanks @jewatkins  and @ikalash !

**Comment by kliegeois** [comment]
Can we close the issue?

**Comment by ikalash** [comment]
Yes.
