### ISSUE TITLE
Broken Albany build due to changes to Trilinos (Phalanx)

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#827]
The Albany builds are broken, due to a missing land ice routine: 

```
/nightlyCDash/repos/Albany/src/LandIce/evaluators/LandIce_UpdateZCoordinate_Def.hpp:238:28: error: no matching function for call to 'LandIce::UpdateZCoordinateGivenTopAndBedSurfaces<PHAL::AlbanyTraits::Residual, PHAL::AlbanyTraits>::addDependentField(PHX::MDField<double, Cell, Node>&)'
```

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=38525

@mperego , @bartgol , @kliegeois , @jewatkins : could one of you please have a look?

**Comment by ikalash** [comment]
Actually is this a Trilinos thing?  I am seeing similar errors in LCM: https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=38525 .

Tagging @lxmota to keep him in the loop on LCM.

**Comment by mperego** [comment]
It probably has to do with this,
https://github.com/trilinos/Trilinos/commit/43d80c9555de0007d0cd8b8bb09089a2e07659ce
so, it should be an easy fix.

**Comment by ikalash** [comment]
Could someone please do this in Albany master today?  I am in an all-day meeting.  I can do it for LCM later.

**Comment by mperego** [comment]
We need to be careful though, and use the nonconst function one only where needed.

**Comment by bartgol** [comment]
Yes, I remember asking Roger to introduce this change, so we could be explicit about our intent, and avoid the warnings. I will fix this.

**Comment by ikalash** [comment]
Thanks @bartgol !

**Comment by ikalash** [comment]
I can actually probably fix this.  I just fixed it in LCM.  Question: it seems the main change is addDependentField was changed to addNonConstDependentField - is there a const version of this function too?  Or is the fix to just replace all instances of addDependentField with addNonConstDependentField?  The latter is what I did in LCM.  @rppawlo

**Comment by mperego** [comment]
@ikalash we have to revert the commit. We only need to replace the nonconst instances of `addDependentField` with `addNonConstDependentField`. For all the other instances we should continue using the (const)  `addDependentField `.

**Comment by ikalash** [comment]
Yes, I figured out that what I did was not correct.  There is actually a very easy fix as it turns out, which I just pushed.  Hopefully the nightlies will be clean tomorrow.

**Comment by rppawlo** [comment]
The const version of addDepedentField is the preferred method. We have come across some difficult use cases when attempting to deprecate the non-const version in applications, so just renamed it for the 14.0 release.

**Comment by ikalash** [comment]
Thanks @rppawlo I figured it out over the weekend.
