### ISSUE TITLE
Weaver nightlies not pushing to CDash site

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#837]
This started a couple weeks ago while I am on foreign travel.  The error looks like this when you log on to the machine, yet curl appears just fine when you check it: 

```
Submit files (using https)
   Using HTTP submit method
   Drop site:https://sems-cdash-son.sandia.gov/cdash/submit.php?project=Albany
   Upload file: /home/projects/albany/nightlyCDashWeaver/build/Testing/20220926-0100/Test.xml to https://sems-cdash-son.sandia.gov/cdash/submit.php?project=Albany&FileName=weaver.sandia.gov___weaver-CUDA-Albany___20220926-0100-Nightly___XML___Test.xml&MD5=0c005162e3712f159f28069e213de236 Size: 896
   Error when uploading file: /home/projects/albany/nightlyCDashWeaver/build/Testing/20220926-0100/Test.xml
   Error message was: Protocol "https" not supported or disabled in libcurl
   Problems when submitting via HTTP
Cannot submit Albany test results!
```
@ikalash is working with the sems team and weaver admins to get the issue resolved.

**Comment by ikalash** [comment]
So when I switch to "-q rhel7W", the nightlies are back up, including tests running / passing (except the performance tests) except there is an error reported upon building the code (even though the build completes): ```/usr/bin/env: python3: No such file or directory``` 

https://sems-cdash-son.sandia.gov/cdash/index.php?project=Albany&date=2022-09-27&filtercount=1&showfilters=1&field1=groupname&compare1=61&value1=Nightly

I checked and there is python3 on weaver.  I am actually not sure what Albany is trying to do using python3 in the build.  Does anyone know?  @jewatkins , @bartgol , @kliegeois .

**Comment by kliegeois** [comment]
Is PyAlbany enabled?
It is strange that this happens during the build yes.

**Comment by ikalash** [comment]
No it's not.  That is what I don't understand...

**Comment by kliegeois** [comment]
There is one Hessian test that uses python (regardless of PyAlbany) but it should be disabled if python is not available.

**Comment by ikalash** [comment]
I think this can be fixed by loading the python3 module.  I will see tomorrow if it fixes the problem and report back.  Still no idea why python is required given the configuration...

**Comment by kliegeois** [comment]
Looks like we can't live without Python anymore 😀
