### ISSUE TITLE
Fix webpage breakdown 

### ISSUE THREAD

**Issue by adityaIyerramesh98** [sandialabs/Albany#838]
Hello contributors, 

Albany's webpage: https://snlcomputation.github.io/Albany
keeps breaking down and is just not viewable. Can someone shed light on this and provide with a modified link/URL to get readthedocs for Albany or anyother workaround? 
Am trying to comprehend Albany's environment along with some tutorial cases to start with. 

Thank you!

**Comment by ikalash** [comment]
@adityaIyerramesh98 : thank you for your interest in Albany.  The correct webpage is this one: https://sandialabs.github.io/Albany/, as Albany is now in the sandialabs space on github.  Please let us know if you have any more questions.

**Comment by adityaIyerramesh98** [comment]
Thank you for a very prompt response, @ikalash !
I'll check out the modified URL.
