### ISSUE TITLE
Recent refactor of GatherSolution introduced usage of `this` inside KOKKOS_LAMBDA, and yet tests pass

### ISSUE THREAD

**Issue by bartgol** [sandialabs/Albany#853]
All the calls to `get_ref`, `get_ref_dot`, and `get_ref_dotdot` are implicitly using `this`. This was not allowed by C++14, but I think CUDA 11 is supporting C++17, including the capture of `*this` in a lambda.

I know Trilinos is about to require C++17 via kokkos, but is that already the case? @jewatkins @mperego @kliegeois do you know?

Using lambdas is much easier to read: no need for declaring operator(), which makes files longer, or to store views in the class just to be able to access them in the operator() call. But I don't want to use lambda at the cost of code correctness. If C++17 is guaranteed to be supported in our cuda builds, then capturing `*this` is fine. If not, I'll have to revert back to functor implementation.

**Comment by kliegeois** [comment]
@bartgol Kokkos requires c++ 17 to build the develop branch. If I recall correctly, Kokkos 4.0 will require c++ 17 and that will propagate the requirement to Trilinos (and us).

I would say go for it.

**Comment by bartgol** [comment]
So it's safe to use KOKKOS_LAMBDA that capture `*this`?

**Comment by jewatkins** [comment]
You need the class one: `KOKKOS_CLASS_LAMBDA`. I tried it a long time ago and it works: https://gitlab-ex.sandia.gov/jwatkin/albany-land-ice-kernel-testing/-/blob/noTrilinos/src/StokesFOResid.cpp#L201
We're still trying to require c++17 in albany testing. We should have it done soon: https://github.com/sandialabs/Albany/issues/842

**Comment by jewatkins** [comment]
i.e. as soon as all albany nightlies have c++17, you'll be able to push

**Comment by bartgol** [comment]
Interesting. Well, the thing is, that stuff is already in master. So I wonder how come our tests pass given that I am using a simple `KOKKOS_LAMBDA` macro in `GatherSolution`...

**Comment by jewatkins** [comment]
Ah okay interesting... not sure why the class one isn't required, maybe they removed the need for it? The c++17 requirement might only be a cuda thing which we already added for our GPU tests: https://github.com/sandialabs/Albany/blob/master/doc/dashboards/weaver.sandia.gov/do-cmake-weaver-trilinos#L128

**Comment by bartgol** [comment]
I suspect the CUDA version we use is actually already allowing implicit capture of `*this`. That said, in E3SM kokkos ports, I've seen lots of cases where the code "works", but cuda-memcheck complains. I'm gonna switch to KOKKOS_CLASS_LAMBDA in my current branch. Thanks!
