### ISSUE TITLE
Failying PyAlbany test in nightly spack build

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#866]
A couple days ago, the PythonAlbany_RSVDsinglePass test began failing in the nightly Spack build.  @kliegeois can you please have a look?  The output from the failed run is attached.
[out.txt](https://github.com/sandialabs/Albany/files/10171881/out.txt)

**Comment by kliegeois** [comment]
I am looking into this @ikalash ! :)

**Comment by kliegeois** [comment]
I am unable to reproduce it with my current version of Trilinos, I uninstall the spack trilinos-for-albany module and I am trying again (it is going to take some time).

**Comment by ikalash** [comment]
It looks like last night the test was OK despite failing 2 nights in a row.  Strange.  I will continue to monitor things to see if the issue crops up again; if not, I will close it.  Thanks for looking into it!

**Comment by kliegeois** [comment]
Strange and I am still unable to reproduce it, sorry.

**Comment by ikalash** [comment]
The spack nightly build has been clean for the past few days, so I will close this issue.

**Comment by kliegeois** [comment]
Thanks for the update @ikalash !
