### ISSUE TITLE
Failing tests on weaver

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#867]
6 tests on weaver started failing between Nov. 16 and Nov. 18:
[FO_GIS_Humboldt_FluxDiv_Tpetra_FROSch](https://sems-cdash-son.sandia.gov/cdash/test/3129707)	[Failed](https://sems-cdash-son.sandia.gov/cdash/test/3129707)	8s 810ms	Completed (Failed)	Broken	[Unstable](https://sems-cdash-son.sandia.gov/cdash/testSummary.php?project=1&name=FO_GIS_Humboldt_FluxDiv_Tpetra_FROSch&date=2022-12-09)
[FO_Hydrology_Steady_Dome_Tpetra](https://sems-cdash-son.sandia.gov/cdash/test/3129733)	[Failed](https://sems-cdash-son.sandia.gov/cdash/test/3129733)	23s 230ms	Completed (Failed)	Broken	[Unstable](https://sems-cdash-son.sandia.gov/cdash/testSummary.php?project=1&name=FO_Hydrology_Steady_Dome_Tpetra&date=2022-12-09)
[FO_Thermo_Humboldt_fluxDiv](https://sems-cdash-son.sandia.gov/cdash/test/3129722)	[Failed](https://sems-cdash-son.sandia.gov/cdash/test/3129722)	15s 770ms	Completed (Failed)	Broken	[Unstable](https://sems-cdash-son.sandia.gov/cdash/testSummary.php?project=1&name=FO_Thermo_Humboldt_fluxDiv&date=2022-12-09)
[FO_Thermo_Humboldt_lubricated](https://sems-cdash-son.sandia.gov/cdash/test/3129723)	[Failed](https://sems-cdash-son.sandia.gov/cdash/test/3129723)	11s 240ms	Completed (Failed)	Broken	[Unstable](https://sems-cdash-son.sandia.gov/cdash/testSummary.php?project=1&name=FO_Thermo_Humboldt_lubricated&date=2022-12-09)
[FO_Thermo_Wet_Bed_FROSch](https://sems-cdash-son.sandia.gov/cdash/test/3129721)	[Failed](https://sems-cdash-son.sandia.gov/cdash/test/3129721)	10s 230ms	Completed (Failed)	Broken	[Unstable](https://sems-cdash-son.sandia.gov/cdash/testSummary.php?project=1&name=FO_Thermo_Wet_Bed_FROSch&date=2022-12-09)
[SteadyHeatConstrainedOpt2D_Dirichlet_Dist_Param_Tpetra](https://sems-cdash-son.sandia.gov/cdash/test/3129641)	[Failed](https://sems-cdash-son.sandia.gov/cdash/test/3129641)	3s 320ms	Completed (Failed)	Broken	[Unstable](https://sems-cdash-son.sandia.gov/cdash/testSummary.php?project=1&name=SteadyHeatConstrainedOpt2D_Dirichlet_Dist_Param_Tpetra&date=2022-12-09)
The Trilinos/Albany commit ids for the point of failure are:
```
Trilinos passed: 1d2b33e
Trilinos failed: db798a8
Albany passed: adeb9c7
Albany failed: 29946ff
```
Looking at FO_GIS_Humboldt_FluxDiv_Tpetra_FROSch, it looks like the sensitivity computation on GPU might have slightly changed. I compared `Sensitivities (0,0) for Distributed Parameters:  (two-norm)` on blake and weaver before/after the change:
```
Before:
CPU: 1.489899943352e+01
GPU: 1.489899943352e+01
After:
CPU: 1.489899943352e+01
GPU: 1.489903682836e+01
```
The other two sensitivities look unchanged so not sure why it only happen on the first one.

@mperego it looks like there might have been some changes related to Piro or sensitivities during that time. Do you know what the issue could be?

**Comment by jewatkins** [comment]
For reference, here are the links for the passing tests:
blake: https://sems-cdash-son.sandia.gov/cdash/test/3064442?graph=status
weaver: https://sems-cdash-son.sandia.gov/cdash/test/3066196?graph=status
And the point right after failure:
blake: https://sems-cdash-son.sandia.gov/cdash/test/3070343?graph=status
weaver: https://sems-cdash-son.sandia.gov/cdash/test/3071383?graph=status

**Comment by mperego** [comment]
That is bizarre. I pushed some changes to Piro and Albany, but they should not have any effect on these tests (not even a rearrangement of operations). I suspect that there is some memory leak or uninitialized value.

**Comment by jewatkins** [comment]
opps, closed this by accident. very odd

**Comment by jewatkins** [comment]
This is fixed. Thanks @mperego! I guess part of the issue is that we didn't have ROL enabled. Should we try to turn it on for the weaver build?

**Comment by mperego** [comment]
If we keep having ROL optional, then it's good to have a build not using ROL. maybe we can rename it so that it's clear rol is not enabled? I could have figured it out earlier that it was just an issue with ROL not been enabled. Basically, it was not transposing the matrix in the adjoint solve. I think I was confused by the other randomly failing tests and the fact that it was a Cuda build.

**Comment by jewatkins** [comment]
Part of the issue is we don't have a consistent Trilinos configuration across the nightly builds. Maybe we can get together and settle on a specific list to use for everything below https://github.com/sandialabs/Albany/blob/master/doc/LandIce/perlmutter/do-cmake-trilinos-prml-gcc#L65?
We could then add a no ROL build. Probably better to be on CPU.

**Comment by bartgol** [comment]
Can't we simply disable the test if ROL is not enabled?

**Comment by mperego** [comment]
Tests that need ROL (all AlbanyAnalysis tests) are already disabled. There was a bug that I introduced when I refactored Piro but now it's fixed. 
The builds for MALI and E3SM don't need to enable ROL.

**Comment by jewatkins** [comment]
> The builds for MALI and E3SM don't need to enable ROL.

Ah okay, then maybe when we have our MALI builds, we can test ROL off there.
