### ISSUE TITLE
Create epetra-free option for Trilinos and Albany in spack Albany build

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#874]

**Comment by ikalash** [comment]
Question: does anyone know if Teko works with Amesos?   Currently, there is a conflict coded in to the Trilinos in spack that prevents Teko from working if Amesos is enabled, which I suspect is stale.

**Comment by mperego** [comment]
Hi Irina, are you talking about Amesos2?  For the Epetra-free buid Amesos should not be enabled.

**Comment by ikalash** [comment]
No, I'm talking about Amesos, but what I wrote above was not quite right - sorry about the confusion.  In the epetra-free spack build, I want to turn on teko but turn off Amesos in Trilinos.  When I do this, I get the following error: 

```
[ikalash@mockba spack-e3sm-project]$ spack --insecure install --dirty --keep-stage albany%gcc@10.1.0+mpas+py+cxx17~epetra 
==> Warning: You asked for --insecure. Will NOT check SSL certificates.
==> Error: trilinos-for-albany '+teko' conflicts with '~amesos'
```
Allegedly, Teko requires Amesos, which I think is not true.  I can fix this but wanted to get some confirmation first.
