### ISSUE TITLE
ComputeBasisFunctionsSide: wrong side ordinal passed to intrepid2 cell tools when computing normals

### ISSUE THREAD

**Issue by bartgol** [sandialabs/Albany#883]
I think this is wrong, but I have no idea why it is not causing issues in master. Perhaps it is, we are just not seeing them?

In `ComputeBasisFunctionsSide`, if the normals are required, we call a few `Intrepid2::CellTools` methods, passing `side` as the `worksetSideOrd`. From the impl of Intrepid2, this integer should be in `[0, num_sides_of_this_cell)`. However, `side` is simply a counter, going from 0 to however many sides are on this sideset (max across all worksets). The fix should be easy: simply use `sideSet.side_local_id(side)` instead (I'm going to do this in my branch).

Assuming my understanding is correct, the question becomes: could this have caused issues? @mperego @mcarlson801 , pinging you as the expert in sidesets and/or basal BCs. Note: I found this (possible?) bug since I was getting 0/0, b/c a normal was in the y direction rather than the z direction, causing an FPE in StokesFOBasalResid

```
    for (unsigned int qp=0; qp<numSideQPs; ++qp) {
      MeshScalarT bx = -normals(sideSet_idx,qp,0)/normals(sideSet_idx,qp,2); // <--- 0/0 since the normal was [0,-1,0]
 ```

**Comment by mperego** [comment]
@bartgol how is it possible that the normal to the bed is `[0, -1 ,0]`? I would expect it to be close to `[0,0,-1]`.

**Comment by bartgol** [comment]
I think that's b/c the wrong side local pos is passed to intrepid, so that intrepid computes stuff on the wrong subcell

**Comment by bartgol** [comment]
Uhm, I think I am misunderstanding some things related to the sideset views. Closing this for now.
