### ISSUE TITLE
Add config option to disable all output to file

### ISSUE THREAD

**Issue by bartgol** [sandialabs/Albany#889]
On some machines, filesystem and/or TPL issues might make writing to file very slow. E.g., on my desktop, right now, I'm getting timers summary containing stuff like
```
 |   |   Albany: Output to File: 21.6071 - 83.6868% [161] {min=21.0195, max=22.0719, std dev=0.444008}
```
which is insane. It makes my tests run ~5x slower, just to write the solution to the mesh. Avoiding to write to file would dramatically increase my turnaround time on some tests.

During development, we often only care about the actual numbers of the solution field(s). Of course, if working on disc infrastructure, we should prob make sure we can write solutions to file correctly, but in general we don't care about output files. Besides, we don't even _check_ the content of output files in our testing.

I am not sure if this is already possible, but I suspect not.

**Comment by ikalash** [comment]
I think if you remove "Exodus Output File" from the .yaml file, it will not do output to Exodus file. 

I kind of like having the Exodus output files dumped by the nightlies b/c I sometimes look at them when I'm trying to do something in Albany, but that does not happen that often these days.

**Comment by ikalash** [comment]
Oh ok, I see.  I don't think Albany has that option currently.
