### ISSUE TITLE
Long tests

### ISSUE THREAD

**Issue by bartgol** [sandialabs/Albany#890]
I noticed that the following tests are very long, even in release mode, due to the large number of timesteps. Is it really necessary to run tests this long?

- `demoPDEs_Advection1D_Scalar_Param_Adjoint_Sens_Explicit`: 107s, for 5,000 time steps.
- `demoPDEs_Advection1D_Scalar_Param_Fwd_Sens_Implicit`: 180s, for 1,000 time steps.
- `demoPDEs_Thermal1D_with_Source_Scalar_Param_Adjoint_Sens_Implicit`: 188s, for 1,000 time steps.

I mean, from their names, I don't think they have very complex physics happening (something like a vortex shedding) that takes time to develop, I think they are just demonstrating a capability, and how to use it. So perhaps running for 25 or 50 time steps is enough?

@ikalash @mperego tagging you guys cause you either created the test (I think) or worked on their reorg.

There are other tests that take a bit too long (even in release mode). E.g., `LandIce_SHMIP_Suite_A1`, which could prob be disabled/removed (it's a subglacial hydrology setting where not using channels is debatable at best). Other GIS tests are not that short either (GIS_20km tests take ~40s each), and I'm not really sure what additional coverage they provide over the GIS_Unstructured tests (@mperego ?).

Ideally, I'd like each test to take 10s or less (in release mode), but I guess <30s is still ok.

Note: I was running tests without writing exo output, to avoid the issue mentioned in #889.

**Comment by mperego** [comment]
@bartgol we could simply run them only when `ENABLE_LARGE_TESTS` is on

**Comment by bartgol** [comment]
Yes, that's a good alternative.

**Comment by bartgol** [comment]
Ok, thanks. At this point I think the option of enabling only if `ENABLE_LARGE_TESTS=ON` (the default) is prob the easiest. Gives room to users/devs to decide what to test.

**Comment by ikalash** [comment]
Sounds good to me.
