### ISSUE TITLE
Can we get rid of FieldRequirements?

### ISSUE THREAD

**Issue by bartgol** [sandialabs/Albany#892]
These vectors are set in the problem, and passed to the discretization...but they are never used! They are ultimately passed to the field container structures, which simply ignore them (the MultiSTKFieldContainer doesn't even take it as a parameter).

They were originally supposed (I think) to serve as a way to check that all required fields were in the mesh, but it seems like a lot of infrastructure just for checking that. Besides, if a field is missing, we will get an error from the DAG check, since the LoadStateField (or similar) evaluator was never created.

This is not urgent, but there are hundreds of lines of code that can be removed. Our disc code is already complex enough to maintain, no need to add extra (and pointless) headaches.

Edit: they are still used in the GenericSTKMeshStruct, as a way of checking that all required fields are loaded from the mesh. But, again, this check is probably not needed (DAG covers it), and extremely heavy in terms of LOC to maintain.

**Comment by mperego** [comment]
I'm in favor of removing them as long as we make sure that Albany (or Phalanx) throws meaningful error messages when the required fields are not available.
