### ISSUE TITLE
Build issues due to ALBANY_MPI flag being undefined

### ISSUE THREAD

**Issue by mcarlson801** [sandialabs/Albany#893]
(This is unrelated to [Trilinos Issue #11487](https://github.com/trilinos/Trilinos/issues/11487) which is the culprit of current failures on cdash. This issue arises after implementing a workaround for the Trilinos issue.)

I'm currently seeing the following error when trying to build Albany:

```/usr/bin/ld: ../../../src/libalbanyLib.so: undefined reference to `Albany::getMpiCommFromTeuchosComm(Teuchos::RCP<Teuchos::Comm<int> const>&)'
collect2: error: ld returned 1 exit status
make[2]: *** [tests/unit/evaluators/CMakeFiles/gatherDistributedParameters_unit_tester.dir/build.make:227: tests/unit/evaluators/gatherDistributedParameters_unit_tester] Error 1
make[1]: *** [CMakeFiles/Makefile2:2073: tests/unit/evaluators/CMakeFiles/gatherDistributedParameters_unit_tester.dir/all] Error 2```

After digging into `Albany_CommUtils.cpp`, it looks like this is undefined because somehow the `ALBANY_MPI` flag is undefined. I took out the check for `ALBANY_MPI` and this built without issue. Anyone have any ideas why this might not be getting defined? I tried defining it as a cmake flag with no success.

Also, @bartgol, @jewatkins, is there ever a case where Albany gets built without MPI enabled? I wonder if we even need some of the logic based on `ALBANY_MPI`.

**Comment by bartgol** [comment]
I think the non MPI case was introduced long time ago. IMHO, we could remove it. Grepping in trilinos, it's already a required TPL for some of the packages we use:
```
$ git grep -w MPI | grep REQUIRED
cmake/tribits/examples/MockTrilinos/packages/panzer/cmake/Dependencies.cmake:  LIB_REQUIRED_TPLS MPI Boost
packages/panzer/disc-fe/cmake/Dependencies.cmake:SET(LIB_REQUIRED_DEP_TPLS MPI)
packages/panzer/dof-mgr/cmake/Dependencies.cmake:SET(LIB_REQUIRED_DEP_TPLS MPI)
packages/panzer/mini-em/cmake/Dependencies.cmake:SET(LIB_REQUIRED_DEP_TPLS MPI)
packages/pike/blackbox/cmake/Dependencies.cmake:  LIB_REQUIRED_TPLS MPI
packages/shylu/shylu_dd/frosch/cmake/Dependencies.cmake:SET(LIB_REQUIRED_DEP_TPLS MPI)
packages/stk/stk_coupling/cmake/Dependencies.cmake:SET(LIB_REQUIRED_DEP_TPLS MPI)
packages/stk/stk_emend/cmake/Dependencies.cmake:SET(LIB_REQUIRED_DEP_TPLS MPI)
packages/stk/stk_integration_tests/cmake_install_test/stk_test_app/CMakeLists.txt:find_package(MPI REQUIRED)
packages/stk/stk_mesh/cmake/Dependencies.cmake:SET(LIB_REQUIRED_DEP_TPLS BLAS MPI)
packages/stk/stk_search/cmake/Dependencies.cmake:SET(LIB_REQUIRED_DEP_TPLS MPI)
```
Notice `stk_mesh` and `dof-mgr`, which we use.

So, in short, I think we should probably remove the possibility of not having MPI...

**Comment by jewatkins** [comment]
Agreed. @ikalash @mperego any reason we should keep `ALBANY_MPI` around? i.e. is it okay to remove all code paths with no mpi.

**Comment by mperego** [comment]
I'm fine removing the no MPI option

**Comment by ikalash** [comment]
I am fine with it too.  Thanks for checking!

**Comment by ikalash** [comment]
Are the build errors we're getting in the nightlies related to this? 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=44375
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=44397

Seems there are also issues with a missing header: 

```
/.../build/TrilinosSerialInstall/include/Ioss_ZoneConnectivity.h(14): catastrophic error: cannot open source file "fmt/ostream.h"
```

**Comment by ikalash** [comment]
Thanks @bartgol .  Is there a plan to get the Albany_MPI_Comm issue resolved?  Would be great if someone could volunteer to fix it.  I don't have time right now to look into it...

**Comment by bartgol** [comment]
I don't know if there's a plan. I am trying to finish the DOF manager refactor asap, since it's been dragging for too long. If nobody volunteered by the time I'm done, I can take it. I got all core/demo tests passing on the dof mgr branch, so hopefully I'm nearing the end...

**Comment by mcarlson801** [comment]
Looks like the PR fixed the issue. Closing.
