### ISSUE TITLE
Issues in SFAD builds on weaver

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#897]
It looks like a bunch of tests are failing on Weaver due to incorrect SFAD side, e.g., https://sems-cdash-son.sandia.gov/cdash/test/3224679

```
 p=3: *** Caught standard std::exception of type 'std::runtime_error' :

 /home/projects/albany/nightlyCDashWeaver/repos/Albany/src/PHAL_Utilities.cpp:39:
 
 Throw number = 1
 
 Throw test that evaluated to true: true
 
 Derivative dimension for <Jacobian> is 16 but ALBANY_SFAD_SIZE is 12!
  - Rebuild with ALBANY_SFAD_SIZE=16
 ```
I thought before there was logic to not run tests that had large sfad sizes in the builds that had small sfad sizes?  Or am I misremembering?

**Comment by jewatkins** [comment]
We're not supposed to run tests on those builds but I don't remember the logic. Let me see if I can find it.

**Comment by jewatkins** [comment]
It looks like this might be the issue https://github.com/sandialabs/Albany/commit/56449cd0fc43792a517ef7364f8049dcb958854d#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL771 from https://github.com/sandialabs/Albany/pull/891. That flag gets used here: https://github.com/sandialabs/Albany/blob/master/doc/dashboards/weaver.sandia.gov/do-cmake-albanySFAD#L16.
Let me try adding it back in.

**Comment by jewatkins** [comment]
Right, just performance tests. Hopefully we can consolidate to these to a single MALI/ALI build and only run certain ALI tests that are applicable to MALI. I need to put some work into the performance test repo & the MALI nightly testing before we can do that though.

**Comment by ikalash** [comment]
Thanks for fixing this @jewatkins !
