### ISSUE TITLE
Failing performance tests on weaver

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#901]
Performance tests are failing: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=44498
Looks like maybe an input file change due to? https://github.com/sandialabs/Albany/pull/894
@bartgol Is it just removing the required fields?

**Comment by bartgol** [comment]
Yes, those entries are no longer used.

**Comment by jewatkins** [comment]
This is fixed.
