### ISSUE TITLE
Failing optimization performance tests on blake

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#911]
optimization performance tests need to be reconfigured: https://sems-cdash-son.sandia.gov/cdash/test/3267272
there are also a few wdg tests that need to be reblessed. Will get to this on Monday.

**Comment by bartgol** [comment]
What are wdg tests? Is wdg=wedge?

**Comment by jewatkins** [comment]
yes

**Comment by jewatkins** [comment]
this has been fixed thanks to @mperego ! 
See https://github.com/sandialabs/ali-perf-tests/commit/abd2001da93b6e272815a64d8e723b78629c129b and https://github.com/sandialabs/Albany/commit/7946f6f01cf1dbdf385de5e82792c8ac0275accf
