### ISSUE TITLE
Issue with Intel compiler on CEE?

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#913]
The nightly tests on CEE using the Intel compiler have been failing for a couple days with the follwing error: 

```
/projects/sems/install/rhel7-x86_64/sems-compilers/tpl/intel-oneapi-compilers/2021.3.0/gcc/8.3.0/base/fptsktp/compiler/2021.3.0/linux/compiler/include/complex:62:3: error: #error "This Intel <complex> is for use only with the Intel C++ compilers!"
``` 
Does anyone know what this means?  It appears there are other errors, e.g., 

```
/projects/sems/install/rhel7-x86_64/sems-compilers/tpl/intel-oneapi-compilers/2021.3.0/gcc/8.3.0/base/fptsktp/compiler/2021.3.0/linux/compiler/include/complex:78:24: error: 'std::complex<double>::_ComplexT std::complex<double>::_M_value' is private within this context
```
I am guessing this is a compiler and not a Trilinos thing?

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=45338

@bartgol , @jewatkins , @mcarlson801 , @mperego

**Comment by jewatkins** [comment]
It looks like its trying to use a gcc build of Trilinos? `/home/ikalash/Trilinos-clean/build-gcc/install/include/`

Also looks like the trilinos intel build has been down. I could take a look, probably a module/config file issue after some sems module update. It might have wait until next week though.

**Comment by ikalash** [comment]
Ah ok, the problem is Trilinos didn't build with the intel compiler b/c the sems team messed up the netcdf module again.  I will let them know.  Closing.
