### ISSUE TITLE
Update CMake min version from 3.17 to 3.23

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#914]
@ikalash @mperego 
Need to do it before https://github.com/trilinos/Trilinos/pull/11583 gets pushed.
Module files that need to be updated:
https://github.com/sandialabs/Albany/blob/master/doc/dashboards/attaway-login1/attaway_modules_intel.sh
https://github.com/sandialabs/Albany/blob/master/doc/dashboards/blake.sandia.gov/blake_gcc_modules.sh
https://github.com/sandialabs/Albany/blob/master/doc/dashboards/blake.sandia.gov/blake_intel_modules.sh

**Comment by jewatkins** [comment]
`cmake/3.22.2` is the default on blake. We can send an email to the admins again.

**Comment by jewatkins** [comment]
email sent. On attaway, looks like we can switch to `cmake/3.25.2` or just use the default cmake instead of sems cmake.

**Comment by ikalash** [comment]
Yes, I saw that email.  Thanks for emailing the blake admins.  I have updated the cmake on attaway.  Worst case scenario, I would build a separate cmake on blake, but I think the admins should update the modules given that a lot of people use Trilinos on that machine.

**Comment by ikalash** [comment]
This is a problem also on cori.  I will open an issue with the support to create a module with a higher cmake.  The only one that is available is 3.22.2.

**Comment by ikalash** [comment]
Actually Cori is going down so I will not bug them...  will just put a high enough cmake there for now.

**Comment by ikalash** [comment]
I think this has been resolved.
