### ISSUE TITLE
Build error on Weaver

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#915]
It looks like there's a build error on Weaver for Albany related to Xpetra: 

```
/.../repos/Trilinos/packages/xpetra/sup/Utils/Xpetra_MatrixMatrix.hpp(388): error: incomplete type is not allowed
```

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=45660

Seems this must be coming from Trilinos.  Does anyone have any insight into the error?  Should we open a Trilinos issue?

**Comment by bartgol** [comment]
No idea. Maybe something changed in Xpetra? Given that it's Friday and probably we would not get a reply today (or might not read it until Monday) anyways, we can wait till Monday to open it, and see if by chance it was a fluke (maybe something went wrong during the clone).

**Comment by ikalash** [comment]
Thanks @bartgol .  Would you mind looking at it on Monday and opening a Trilinos issue as needed?  I will be on foreign travel at SIAM CS&E.

**Comment by ikalash** [comment]
Similar error occurred on Cori.  I opened a Trilinos issue, see above.

**Comment by ikalash** [comment]
This has been resolved by turning off Xpetra EpetraExt; see https://github.com/trilinos/Trilinos/issues/11606 for more details.
