### ISSUE TITLE
Configure failures due to upcoming 14.1 Trilinos release

### ISSUE THREAD

**Issue by mcarlson801** [sandialabs/Albany#920]
Albany configuration is failing on the nightlies and on Perlmutter with the following CMake error:

> CMake Error at CMakeLists.txt:31 (FIND_PACKAGE):
>   Could not find a configuration file for package "Trilinos" that is
>   compatible with requested version "13.1".
> 
>   The following configuration files were considered but not accepted:
> 
>     /home/projects/albany/nightlyCDashWeaver/build/TrilinosInstall/lib/cmake/Trilinos/TrilinosConfig.cmake, version: 14.1
> 
> 
> 
> -- Configuring incomplete, errors occurred!

It looks like this is due to https://github.com/trilinos/Trilinos/pull/11645 updating the Trilinos version to 14.1 while Albany's CMakeLists.txt requires *exactly* 13.1. I can update this to 14.1 but I wanted to ask: Is it intentional that we require an exact version and not a minimum version or range of versions?

**Comment by mperego** [comment]
@bartgol @jewatkins any idea why we are requiring a specific version of Trilinos?

**Comment by ikalash** [comment]
I had the same question when I was looking at the code to try to fix some build failure that was brought in a few weeks ago...  might be left over from older times.

**Comment by bartgol** [comment]
I think that, since we test against current trilinos at night, it's healthy to put a min version required, since we can't guarantee bwd compatibility. Notice that, without `..$VERSION_MAX` and without the `EXACT` keyword, we should accept any subsequent version.

That said, I don't know why it fails. It would be a good idea to check that the trilinos install folder contains all the expected cmake config files, including a version one. Perhaps something goes awry while installing trilinos.

**Comment by mcarlson801** [comment]
> Notice that, without ..$VERSION_MAX and without the EXACT keyword, we should accept any subsequent version.

Ah ha, I misread the documentation originally. Looking at the find_package documentation some more though I think you are right. What we had should have acted as a minimum version. Not sure why it failed.

**Comment by jewatkins** [comment]
does it configure without that line? that seems to be the culprit

**Comment by mcarlson801** [comment]
> I still think it's possible that the trilinos installation does not complete correctly. Our usage of `find_package` is straight from the book.

I checked and `TrilinosConfig.cmake` is in the install folder with `set(Trilinos_VERSION "14.1")`.

Anyway, updating the required version to 14.1 fixed the configuration issue on Weaver and Perlmutter (and I assume will fix mockba too). Shall I go ahead and push it?

**Comment by bartgol** [comment]
Yeah, if things work, we'll just blame Murphy, and be grateful is now working.
