### ISSUE TITLE
Add +optimization or +inversion option to Albany spack build

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#927]
Per the discussion at today's Albany meeting, there is a feature request to add a +optimization or +inversion option to the Albany spack build, which would turn on the following options in Trilinos: 

ROL
FROSCh
SuperLU 

All of these are off by default. 

Question for the team:

- Which option do you prefer, +optimization or +inversion? 
- Are there any other options that the new flag should turn on besides the above three?

Tagging some of the folks who may be interested: @mperego , @jewatkins , @bartgol , @trhille , @matthewhoffman .

**Comment by mperego** [comment]
@ikalash I believe that ROL is enabled by default (@trhille was able to run an optimization problem), so you could turn it off in the default build. 
For GPU builds, SuperLU needs to be turned off.
`+optimization` is fine with me. Is `PyAlbany` built by default?

We could add the `mesh_depends_on_params` option to the optimization build, which is used when we invert for bed topography, , but it slows things down, so it's probably better if one is deliberate about it.

What about Epetra? Is that off in both builds?

**Comment by mperego** [comment]
@bartgol it's probably OK to do `+optimization+mesh_depends_on_params`.

**Comment by ikalash** [comment]
No, PyAlbany is not built by default.  You have to do +py.  I will add +optimization given the above discussion.  There is a +epetra flag, which is on by default in Albany.  What do you mean by is Epetra off in both builds?  You want it to be off if we are doing +optimization, +py and +mesh_depends_on_params?  Or off by default?

**Comment by mperego** [comment]
Thanks. I would turn epetra off by default in either spack build.

**Comment by mperego** [comment]
(In Trilinos as well)

**Comment by ikalash** [comment]
I am working on this finally.  Some questions for @mperego :

- Is SuperLU a required dependence for FROSch?
- I noticed that there is a superlu and superlu-dist option in Trilinos.  Which is the one you prefer?

**Comment by mperego** [comment]
Hi Irina. I would go with superlu instead of superlu-dist.  Superlu it's not a required dependency of FROSch, one e can use, e.g., klu instead of superlu. Thanks!

**Comment by ikalash** [comment]
Thanks @mperego!  Will let you know when this is done.

**Comment by ikalash** [comment]
I'm testing stuff and have another question.  I thought ROL should only be turned on when we do +optimization, but appears it's needed for the pyAlbany interface: 
```
 /tmp/ikalash/spack-stage/spack-stage-albany-develop-6max3n7hkg36yrpvpznokw4lt65yi45i
            /spack-src/pyAlbany/src/Albany_Interface.cpp:42:10: fatal error: ROL_Types.hpp: No s
            uch file or directory
     949       42 | #include "ROL_Types.hpp"
     950          |          ^~~~~~~~~~~~~~~
```
@kliegeois , is this intended?  I'd think you could use the pyAlbany interface w/o ROL.

**Comment by mperego** [comment]
That's a good point Irina. There are definitely some PyAlbany capabilities that can be used without ROL, however I'm not sure it is worth to make ROL an optional dependency for PyAlbany. We can discuss this at the Albany meeting. 
Maybe for the basic spack buid you can disable Pyalbany, and instead of the `optimization ` flag we can have an `analysis` flag that includes PyAlbany. The basic build would be used mainly for MALI, which does not require PyAlbany.

What about Epetra, did we agree to remove Epetra stack from Trilinos and Albany in both build? This would be my preference.

**Comment by ikalash** [comment]
Before we just had ROL on by default.  Any reason to not have that going forward?

I made epetra off by default, yes.

**Comment by mperego** [comment]
It's just that it is not used in MALI. So I was thinking it would make sense to have a build with only the packages needed by MALI.

**Comment by ikalash** [comment]
But does it hurt to have it on?  It shouldn't.  It could increase build times but my guess is not by much.  I am worried about having somewhat vague flags like "analysis".  +py is clear, +analysis is not clear - I would have no idea that "analysis" would turn on pyAlbany w/o looking at the package.py

**Comment by mperego** [comment]
It does not hurt until there is an issue with `ROL`.
It's OK with me to have the user explicitly add PyAlbany with `+py` (which would include `ROL`) and to keep the name `+optimization` (which include `ROL`, `FROSch` and `SuperLU`) as discuss before.   I would not include `ROL` or `PyAlbany` by default in the basic build.

In terms of testing, we could test the basic build, and a build with
`+py+optimization+mesh_depends_on_params.`

**Comment by ikalash** [comment]
Ok, I will go ahead and put in that logic.

**Comment by mperego** [comment]
Thanks!

**Comment by ikalash** [comment]
@kliegeois : I have a feature request.  Can we have Albany throw if trying to enable pyAlbany and ROL is not on in Trilinos?  If ROL is a requirement and the code will have missing headers if ROL wasn't on and PyAlbany is requested, PyAlbany actually has a dependency on ROL.

**Comment by kliegeois** [comment]
@ikalash sure, I should have done that.

**Comment by kliegeois** [comment]
Done in https://github.com/sandialabs/Albany/commit/af9bef206954dcdcf80a9d6625de45ec1f96323b .

**Comment by ikalash** [comment]
Thanks @kliegeois !  

I have finished this finally.  I added documentation to the spack wiki (https://github.com/sandialabs/Albany/wiki/Building-Albany-using-Spack) and added +optimization in the nightly testing of the spack build.  My apologies that this took so long!
