### ISSUE TITLE
Failing tests in clang CEE build

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#930]
All the tests in the clang CEE build are failing due to seg faults: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=47293 .  Curiously the debug clang build is OK.  Could be some system related thing...  I will see what happens if I build/run the code from scratch.

**Comment by ikalash** [comment]
Building from scratch / running has no problems.  Will see what happens in subsequent nights...

**Comment by ikalash** [comment]
I looked at this some more today, including moving to a different machine.  When the nightly test scripts create the Albany build, all tests seg fault.  When I build from scratch using the Trilinos build created by the scripts, the tests pass.  I am stumped on this, and am afraid I will have to punt on it for now b/c I don't have time to troubleshoot it...

I have deactivated the clang CEE release build.  The clang CEE debug build is still up.  If anyone is willing to take this on in the next couple of weeks while I'm traveling, that would be great.  I'm happy to provide scripts to reproduce the problem.

**Comment by ikalash** [comment]
So I've finally had a chance to look into this problem, and have some additional info.  Here is what I have observed: 

- The following PR by @bartgol merged on 4/11 is what broke the code.  I verified this through bisection.  https://github.com/sandialabs/Albany/commit/3ded89bf8043c5b11b041a7e38e44753a06d3fd6 
- The problem (segfault) happens only when Albany is built using the nightly testing cdash builds with clang + release.  If I build the code straightup with cmake and clang + release, things are fine.
- The issue does not show up in any other builds, including the clang + debug CEE build.
- The issue is not specific to any of the cee-compute001 nodes - seems to be happening everywhere.

I attempted to debug the problem on the SteadyHeat2D/inputT.yaml test case using print statements and traced it down to this line: https://github.com/sandialabs/Albany/blob/master/src/InitialCondition.cpp#L267 .  When I print elemLID, in the "good" builds, I get 0.  In the clang cee-compute001 compute build, I get some crazy number, e.g., 192267392, which is clearly wrong.  Interestingly every time I run, I get a different number!

I am not sure how we want to proceed here...  I have a worry that there is an underlying problem somewhere in the code (Trilinos or Albany) that is causing this (an initiated value perhaps), but it is weird that it doesn't show up in the other builds.  Thougthts?  @kliegeois , @mperego , @bartgol .

I am attaching my InitialCondition.cpp (with print statements) and some of the output.  I think @bartgol would probably be the best one to try to debug this if we decide to pursue the debugging.

[InitialCondition.cpp.txt](https://github.com/sandialabs/Albany/files/11525588/InitialCondition.cpp.txt)  
[out-cee-compute001-clang.txt](https://github.com/sandialabs/Albany/files/11525583/out-cee-compute001-clang.txt)
[out-mockba-gcc.txt](https://github.com/sandialabs/Albany/files/11525584/out-mockba-gcc.txt)

**Comment by bartgol** [comment]
The only thing I can think of is uninitialized memory. When a page is grabbed from main memory, the OS always inits it to 0 (for security reasons). OTOH, if memory is grabbed from a page that was already assigned to the process, it is left untouched (and could therefore contain garbage).

Running thgough valgrind should quickly verify this. It can be done in the "good" build as well. Debug or release should not matter, although a debug build may give more human-readable context if an error is found (either way, I would obviously not use a debug build of trilinos, since that would just take forever).

**Comment by ikalash** [comment]
Thanks for the reply @bartgol .  I agree that it sounds like uninitialized memory. 
 Unfortunately this only happens in the release build.  I think the easiest thing for you to do would be to just run the nightly test executable through valgrind.  It can be found here on cee-compute001: /scratch/albany/build/Albany64BitClang .  You can edit the source code here, if needed, to test things: /projects/albany/nightlyAlbanyCDash/repos/Albany .  Please let me know if there are issues with permissions.  Please keep me posted on what you learn, and thanks again for looking at this!

**Comment by ikalash** [comment]
Thanks for doing these tests @bartgol !  I am not surprised that things are clean with gcc, as the error is not encountered there.  What is the error valgrind shows in the cee clang build out of curiosity?  I agree that it may not be worth pursuing this further given our goals and the behavior.  I would suggest trying a different version of clang but then it would have to be a non-sems module.

**Comment by bartgol** [comment]
@ikalash side question: do you think we can switch our scripts to use shared libs rather than static? Building albany takes forever b/c of linking, especially if debug symbols are present... It took me like 3 minutes to link the Albany executable...

**Comment by bartgol** [comment]
I digged a bit on the valgrind error, and it is quite nonsensical.

Valgrind claims that line [267](https://github.com/sandialabs/Albany/blob/9d425fdf8e3a12866be4a4cd5fb0a634fdfedda7/src/InitialCondition.cpp#L267) of InitialConditions.cpp (the one that Irina found to be the problem) is an error, since we're accessing memory already freed. This is where it gets nonsensical: valgrind claims that memory was freed by ParameterList destructor, and allocated inside `getValidInitialConditionParameters` at the top of the file. It is basically claiming that the `elem_lids` array is aliasing some memory inside a ParameterList. That seems absolutely impossible to me, and the lack of other hints is preventing me from making any further guess.

I will put a few more print statements, hoping to intercept the error earlier (assuming it's a legit error), but I am starting to fear that this error is out of our responsibility...

**Comment by ikalash** [comment]
> I digged a bit on the valgrind error, and it is quite nonsensical.
> 
> Valgrind claims that line [267](https://github.com/sandialabs/Albany/blob/9d425fdf8e3a12866be4a4cd5fb0a634fdfedda7/src/InitialCondition.cpp#L267) of InitialConditions.cpp (the one that Irina found to be the problem) is an error, since we're accessing memory already freed. This is where it gets nonsensical: valgrind claims that memory was freed by ParameterList destructor, and allocated inside `getValidInitialConditionParameters` at the top of the file. It is basically claiming that the `elem_lids` array is aliasing some memory inside a ParameterList. That seems absolutely impossible to me, and the lack of other hints is preventing me from making any further guess.
> 
> I will put a few more print statements, hoping to intercept the error earlier (assuming it's a legit error), but I am starting to fear that this error is out of our responsibility...

Thanks for digging, @bartgol .  Let me know what you find and if you think this is something we should punt on.  I would be OK with that.  I can deactivate the build if that's what we decide.  Curiously the clang debug nightly build is just fine, which to me is bizarre.

**Comment by ikalash** [comment]
> @ikalash side question: do you think we can switch our scripts to use shared libs rather than static? Building albany takes forever b/c of linking, especially if debug symbols are present... It took me like 3 minutes to link the Albany executable...

I don't see why we wouldn't be able to build shared libs.  I actually don't see anything in the configure scripts that are telling the code to do a static build, except the superlu library that is being linked is a static .a one.  Are static libs on by default?  They must be.  I can try to switch it, sure.

**Comment by ikalash** [comment]
It actually looks like there's only a .a superlu library on CEE in the sems modules.  But we can use KLU instead of superlu, I think.

**Comment by ikalash** [comment]
Thanks @bartgol .  I am testing the shared lib build now.  If there are no problems, I'll change the build scripts to build shared libs.

**Comment by ikalash** [comment]
This has indeed been fixed according to the nightlies.  Thanks @jewatkins and @bartgol !
