### ISSUE TITLE
Weaver nightlies failing

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#932]
All the weaver nightlies are failing: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=47336 . 

It looks like everything in the code is broken this week, sigh...

**Comment by mcarlson801** [comment]
I went ahead and tried running the tests again on Weaver using the nightly executable and an executable I built a few days ago and both show all tests passing. The error was that GPUs weren't visible so I'm thinking this must have been a system issue. Either way, I can't replicate it. Should we give it another day?

**Comment by ikalash** [comment]
It's a game of wack-a-mole!  It is driving me crazy...  this is like the worst possible time - I have 4 proposals, a talk and a poster to prepare before I take off on foreign travel next Thursday....

**Comment by mperego** [comment]
> It's a game of wack-a-mole! It is driving me crazy... this is like the worst possible time - I have 4 proposals, a talk and a poster to prepare before I take off on foreign travel next Thursday....

@ikalash, yeah it's frustrating but I'm glad to see that @mcarlson801 @jewatkins and @bartgol are on top of the issues that came up this week and they'll get sorted out. Some of the isolated test failures might take some more time but I don't see any big concern.

**Comment by ikalash** [comment]
It would be great if others could monitor the nightlies and be proactive in fixing some of the stuff, esp. while I am on travel.

**Comment by jewatkins** [comment]
> It would be great if others could monitor the nightlies and be proactive in fixing some of the stuff, esp. while I am on travel.

I can take care of the issue posting/assigning while you're on travel. Just let me know the dates to start monitoring.

**Comment by ikalash** [comment]
Thanks @jewatkins , I really appreciate it!  I'll be out 4/20-5/2.  I can access the SRN now through DAAS which on foreign travel but for some reason my DAAS workstation doesn't let me access the intern CDash site - I have to log on to each machine to check what happened.  So if you can monitor in my absence that would be great!

**Comment by jewatkins** [comment]
I don't see this issue anymore.
