### ISSUE TITLE
Albany link errors having to do with blas/mkl with Intel compiler

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#933]
Starting on 4/11, Albany stopped building on CEE and attaway with an intel compiler: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=47333
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=47330

There are link errors having to do with mkl and blas libraries.  I originally thought the problem was in Trilinos but it appears it's not (see https://github.com/trilinos/Trilinos/issues/11788 and discussion therein).  @jewatkins it would be great if you could have a look at this.  My attempts to fix / triage it have been unsuccessful and I won't have more time to devote to this before my upcoming trip.

**Comment by jewatkins** [comment]
So I noticed you swapped boost lib: https://github.com/sandialabs/Albany/commit/dcb2dd380c0779ac7006d335e5ca3d2669275ccd I actually dropped the need for boost libraries in my build (we don't need them, just the include dir) and I forgot to push.

I'm going to try this build myself right now.

**Comment by jewatkins** [comment]
I get the failure too. So looking at the commit history, this issue coincides with Luca's big PR: https://github.com/sandialabs/Albany/commit/3ded89bf8043c5b11b041a7e38e44753a06d3fd6. @bartgol any reason to believe your changes may have stirred up some intel linking issues? I'll keep looking.

**Comment by jewatkins** [comment]
Ah I bet it's this: https://github.com/sandialabs/Albany/commit/3ded89bf8043c5b11b041a7e38e44753a06d3fd6#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL192

Let me try adding `-mkl`

**Comment by bartgol** [comment]
I removed that line. In the spirit of CMake, I don't think grabbing a var containing all flags, and stuffing them inside Albany, is the way to go.

My driving motivation for rm-ing it was that I wanted to build albany in DEBUG mode, but using trilinos in RELEASE mode (or else compiling takes too long). Since the DEBUG build does not add `-O0` in CMake (by default), the last opt flag came from trilinos flags, so even a DEBUG build would end up being RELEASE, when linking against Trilinos.

Notice that all important flags _should_ be attached to _some_ trilinos target, so we should get them (provided they are in the PUBLIC interface of the tgt). The only flags that CMake does not attach to the target are the debug/opt flags.

If the error is indeed to to a lack of `-mkl`, then I wonder if our trilinos build adds `-mkl` by hand (rather than relying on some CMake logic). If so, then I would prefer to add it to albany also via command line extra flags, and keep the albany-trilinos dependency at a cmake-target level.

**Comment by jewatkins** [comment]
yeah that was the fix, I'll go ahead and update the scripts.

I think its fine to not bring in trilinos cmake flags but we need to update the nightlies that relied on that. Again, to reiterate what I've been saying during every albany meeting, this would be a lot easier to do if we had a consistent trilinos configuration... who knows how many cmake scripts are out there that will run into variations of this same issue.

**Comment by ikalash** [comment]
Thanks so much for tracking this down / fixing it @jewatkins !  We can close this tomorrow if the dashborads on cee-compute004 and attaway are clean.  I have an issue open with the sems team about the missing sems-boost lib dir (I think it was not mounted properly, which has happened before).  I switched to a different boost so that the build would run.  I didnt realize the boost lib dir is no longer needed.  It's fine to remove it in this case - thanks for doing that!  Let me know if you need me to update any of the local scripts used on attaway/CEE to reflect the change.

**Comment by jewatkins** [comment]
@ikalash actually the fix is more complicated then I thought because it requires a different do-cmake-albany file for intel. I think you might be able to fix your scripts faster if I create a PR with the new albany file. I'll post it and you can let me know.

**Comment by ikalash** [comment]
Sounds good @jewatkins .  Just LMK when things are ready for me to try / test.

**Comment by bartgol** [comment]
@jewatkins Are we adding `-mkl` manually to trilinos? I thought Trilinos handled mkl like any other TPL. In my mind, it would find the lib, link it against some trilinos pkg, and then the flag would be transferred to downstream apps as soon as they linked against those packages.

**Comment by jewatkins** [comment]
Yes, we add -mkl manually with a static library. I tried various variations a long time ago and this seemed to be the most reliable across all platforms. There's some discussion here if you want to take a look: https://github.com/trilinos/Trilinos/issues/11788. There may be a better way to do this.

**Comment by bartgol** [comment]
Ok, let's ask them. I don't think Albany should be checking this kind of detail, it should be fully handled inside trilinos, just like any other TPL. I posted a comment there, let's see what they say.

**Comment by jewatkins** [comment]
attaway build is still down, I'll investigate

**Comment by jewatkins** [comment]
attaway is down today so I'll look at it later...

**Comment by jewatkins** [comment]
I think all these issues are fixed. There's something odd going on with the icc/gcc-debug cee builds but I don't think it's compiler related.
