### ISSUE TITLE
Failing tests: Ifpack not found

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#935]
@ikalash @mperego Lots of tests are failing, I think due to https://github.com/trilinos/Trilinos/pull/11739
https://sems-cdash-son.sandia.gov/cdash/test/3398184
```
 Error, the parameter {name="Ifpack Settings",type="ParameterList",value="..."}
 in the parameter (sub)list "Albany Parameters->Piro->NOX->Direction->Newton->Stratimikos Linear Solver->Stratimikos->Preconditioner Types->Ifpack"
 was not found in the list of valid parameters!
 
 The valid parameters and types are:
   {
     "Prec Type" : string = ILUT
     "Overlap" : int = 0
     "half precision" : bool = 0
     "Ifpack2 Settings" : ParameterList = ...
     "VerboseObject" : ParameterList = ...
   }
```
I thought the plan was to get rid of all Epetra/Ifpack tests? What's the status of that?

@bartlettroscoe Is there a simple fix for this or do we basically have to rip out all usage of ifpack?

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe Is there a simple fix for this or do we basically have to rip out all usage of ifpack?

@jewatkins, that error is quite strange.  Why is there an "Ifpack2 Settings" sublist under the "Ifpack" sublist?
 
Can you please attach the full input PL (in XML or YAML form)?

**Comment by jewatkins** [comment]
I'm not sure where "Ifpack2 Settings" comes from. Here are the inputs:
https://github.com/sandialabs/Albany/blob/master/tests/corePDEs/ContinuationHeat1D/input.yaml#L101

**Comment by mperego** [comment]
@bartlettroscoe should we get rid of places where we set the Ifpack2 preconditioning strategy factory? E.g.
https://github.com/sandialabs/Albany/blob/master/src/Albany_SolverFactory.cpp#L53-L58

**Comment by mperego** [comment]
@jewatkins I guess the idea is to keep Epetra around until it becomes unsustainable to do so. Which might happen soon.

**Comment by bartlettroscoe** [comment]
> @bartlettroscoe should we get rid of places where we set the Ifpack2 preconditioning strategy factory? E.g. [`master`/src/Albany_SolverFactory.cpp#L53-L58](https://github.com/sandialabs/Albany/blob/master/src/Albany_SolverFactory.cpp?rgh-link-date=2023-04-18T16%3A36%3A26Z#L53-L58)

Yes, but not doing so should not break things.  That might suggest a defect got added in the commit https://github.com/trilinos/Trilinos/pull/11739/commits/f126ecf6df804c54f8a1b266ab8f148119cc1964.

**Comment by bartlettroscoe** [comment]
> I'm not sure where "Ifpack2 Settings" comes from. Here are the inputs: [`master`/tests/corePDEs/ContinuationHeat1D/input.yaml#L101](https://github.com/sandialabs/Albany/blob/master/tests/corePDEs/ContinuationHeat1D/input.yaml?rgh-link-date=2023-04-18T16%3A16%3A58Z#L101)

@jewatkins, the above exception message says the sublist "Ifpack2 Settings" is sublist of valid parameters.  Not sure how that would happen.  I would need to add a Trilinos test that duplicates the Albany use case and see if see if I can get the same exception.

**Comment by jewatkins** [comment]
https://github.com/sandialabs/Albany/blob/master/src/Albany_SolverFactory.cpp#L53-L58 doesn't seem correct, I'll try making that a runtime argument and see what happens.

**Comment by ikalash** [comment]
Also broken in LCM: https://sems-cdash-son.sandia.gov/cdash/viewTest.php?onlyfailed&buildid=47553 .  Tagging @lxmota .  I will propagate fixes once Jerry makes them to main Albany.
