### ISSUE TITLE
PyAlbany tests failing on blake-gcc

### ISSUE THREAD

**Issue by jewatkins** [sandialabs/Albany#942]
I fixed the mpi issue with pyalbany on blake-gcc but I'm now getting the following error:
```
Traceback (most recent call last):
  File "thermal_steady.py", line 44, in test_all
    theta_star, I_star, F_star, P_star = ee.evaluateThetaStar(l, problem, n_params)
  File "/ascldap/users/jwatkin/LandIce/Albany/build-blake-gcc-serial/pyAlbany/PyAlbany/ExtremeEvent.py", line 511, in evaluateThetaStar
    error = problem.performAnalysis()
RuntimeError: /ascldap/users/jwatkin/LandIce/Albany/src/utility/Albany_ThyraUtils.cpp:996:
Throw number = 1
Throw test that evaluated to true: true
Error in getLocalData! Could not cast Thyra_Vector to any of the supported concrete types.
```
I suspect pyAlbany hasn't been tested with the DOFManager changes in #861 since blake-gcc has been down since Feb. and it's the only build that tests it. Also it looks like maybe there was some thyra changes in that PR. @bartgol @kliegeois Any ideas what the issue could be? The nightlies should produce the same error tomorrow, I will link it then.

**Comment by kliegeois** [comment]
Oh yes, this is most likely due to the PR that I merged today! I forgot to update PyAlbany. I will fix this tomorrow.

**Comment by kliegeois** [comment]
I reopened the issue to track its status tomorrow or later this week.
This should be fixed but let's wait for the NB.

**Comment by kliegeois** [comment]
Those tests passed last night so I am closing this issue.
