### ISSUE TITLE
Failing LandIce test due to cubature degree input

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#958]
There's a failing land ice test b/c its input file was not modified to have the new 'cubature degree' required parameter: https://sems-cdash-son.sandia.gov/cdash/test/3452094 .  Could someone please fix this?

@bartgol , @mperego , @kliegeois

**Comment by mperego** [comment]
Hi @ikalash PR #956 should fix it.

**Comment by ikalash** [comment]
Thanks @mperego .  I am also trying to figure out why we're getting a Cubature Degree error for the CismAlbany test - see here: https://sems-cdash-son.sandia.gov/cdash/test/3452144.  This is the relevant input file: https://github.com/sandialabs/Albany/blob/master/tests/landIce/CismAlbany/inputFiles/input_standalone-albanyT.yaml .  I don't get why 'Cubature Degree' is being asked for for 'upperside', which is a side set not a nodeset.  What am I missing?  I tried adding the cubature degree under the SS specifications, but the option was not recognized.

**Comment by mperego** [comment]
@ikalash the commit I just pushed should fix the CISM failure.

**Comment by ikalash** [comment]
@mperego : yes it's the only CISM failure now - I fixed already the ones on the CISM side by changing ali_driver.cpp.  Thanks for fixing this!  Lets see if the issue goes away when your PR is merged in.

**Comment by ikalash** [comment]
This has been resolved.  Thank you!
