### ISSUE TITLE
Failing weaver nightlies

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#970]
The Weaver Trilinos build is failing, it looks like due to Kokkos: 

https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=51247

```
/.../repos/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp(1319): error: static assertion failed with "Incompatible View copy construction"
```
@jewatkins , @mcarlson801 : could one of you please take a look?

**Comment by jewatkins** [comment]
This is the stack trace:
```
/.../repos/Trilinos/packages/kokkos/core/src/Kokkos_View.hpp(1319): error: static assertion failed with "Incompatible View copy construction"
          detected during:
            instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::View<RT, RP...> &, std::enable_if_t<Kokkos::Impl::ViewMapping<Kokkos::View<DataType, Properties...>::traits, Kokkos::View<RT, RP...>::traits, Kokkos::ViewTraits<DataType, Properties...>::specialize>::is_assignable_data_type, void> *) [with DataType=const int *, Properties=<Kokkos::Device<Kokkos::CudaUVMSpace::execution_space, Kokkos::CudaUVMSpace::memory_space>>, RT=std::add_const_t<int> *, RP=<Kokkos::Device<Kokkos::CudaSpace::execution_space, Kokkos::CudaSpace::memory_space>, void, void>]" 
/.../repos/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp(8471): here
            instantiation of "void Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node>::transferAndFillComplete(Teuchos::RCP<Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node>> &, const Tpetra::Details::Transfer<LocalOrdinal, GlobalOrdinal, Node> &, const Teuchos::RCP<const Tpetra::Details::Transfer<LocalOrdinal, GlobalOrdinal, Node>> &, const Teuchos::RCP<const Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node>::map_type> &, const Teuchos::RCP<const Tpetra::CrsMatrix<Scalar, LocalOrdinal, GlobalOrdinal, Node>::map_type> &, const Teuchos::RCP<Teuchos::ParameterList> &) const [with Scalar=Tpetra::longlong, LocalOrdinal=int, GlobalOrdinal=Tpetra::longlong, Node=Tpetra::Tpetra_KokkosCompat_KokkosCudaWrapperNode]" 
/.../repos/Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp(8927): here
```
It looks like there might be an issue with `Trilinos/packages/tpetra/core/src/Tpetra_CrsMatrix_def.hpp(8471)`

@jhux2 you recently pushed some changes to Tpetra_CrsMatrix_def.hpp:
https://github.com/trilinos/Trilinos/commit/9dd1584105295f197af0811c60d6efc7a486cfdd#diff-459768940c57c556763295d259e08372966e1c385733f85b2f52708a68c6f3caR8471
Any reason the views might conflict on that line? Particularly when using CUDA UVM? Not sure if trilinos tests that anymore.

**Comment by mcarlson801** [comment]
I just built this version of Trilinos with UVM off on Perlmutter and didn't run into the issue. The UVM-on build hasn't gotten to this point but if it fails with the same issue, I'll comment here.

**Comment by mcarlson801** [comment]
Yep, the same error happens on Perlmutter with UVM on but not with it off. The stack trace seems to indicate that it is an issue with CudaUVM so this just confirms that.

**Comment by jewatkins** [comment]
Looks like that PR might get reverted: https://github.com/trilinos/Trilinos/pull/12115

**Comment by jhux2** [comment]
Yes, that's my commit.  EMPIRE hit the same thing.  I'm reverting, will look into the problem.

**Comment by ikalash** [comment]
It seems this is resolved (likely by Jonathan's revert)  Closing.
