### ISSUE TITLE
Question: remove nightly test scripts for machines no longer part of nightly testing?

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#983]
I have a question for everyone.  I noticed when going through the nightly dashboard scripts that some of the machines for which scripts exist are no longer running nightly tests, e.g., mayer, cori (https://github.com/sandialabs/Albany/tree/master/doc/dashboards) .  Can I remove these?  Or people prefer to keep them for archival purposes?  Note that they will still be part of the repo if they are removed, and can be recovered by checking out an older version of the code.

**Comment by bartgol** [comment]
I'm for removing them. Legacy code/scripts only make the repo harder to navigate, for no particular reason. If one needs old stuff, they can always check out old code.

**Comment by ikalash** [comment]
Thanks @bartgol .  I will remove.  We can always restore later if needed.

**Comment by ikalash** [comment]
Done.  Closing.
