### ISSUE TITLE
Failing thermal tests

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#989]
It looks like the following thermal tests are failing: 
```
demoPDEs_Thermal1D 
demoPDEs_Thermal1D_with_Source_Scalar_Param_Fwd_Sens_Implicit 
demoPDEs_Thermal2D_BackwardEuler_with_Source_Scalar_Param_Adjoint_Sens
demoPDEs_Thermal2D_BackwardEuler_with_Source_Scalar_Param_Fwd_Sens
```
All the tests are using Tempus and the error looks like this: 

```
WARNING: NOX::Direction::Newton::compute() - Linear solve failed to achieve convergence - using the step anyway since "Rescue Bad Newton Solve" is true 
WARNING: NOX::Direction::Newton::compute() - Linear solve failed to achieve convergence - using the step anyway since "Rescue Bad Newton Solve" is true 
WARNING: NOX::Direction::Newton::compute() - Linear solve failed to achieve convergence - using the step anyway since "Rescue Bad Newton Solve" is true 
WARNING: NOX::Direction::Newton::compute() - Linear solve failed to achieve convergence - using the step anyway since "Rescue Bad Newton Solve" is true 
WARNING: NOX::Direction::Newton::compute() - Linear solve failed to achieve convergence - using the step anyway since "Rescue Bad Newton Solve" is true 
WARNING: NOX::Direction::Newton::compute() - Linear solve failed to achieve convergence - using the step anyway since "Rescue Bad Newton Solve" is true 
WARNING: NOX::Direction::Newton::compute() - Linear solve failed to achieve convergence - using the step anyway since "Rescue Bad Newton Solve" is true 
WARNING: NOX::Direction::Newton::compute() - Linear solve failed to achieve convergence - using the step anyway since "Rescue Bad Newton Solve" is true 
WARNING: NOX::Direction::Newton::compute() - Linear solve failed to achieve convergence - using the step anyway since "Rescue Bad Newton Solve" is true 
WARNING: NOX::Direction::Newton::compute() - Linear solve failed to achieve convergence - using the step anyway since "Rescue Bad Newton Solve" is true 
1     1.000e+03  1.000e+03    STEP FAILURE!! - Solution Status = FAILED
 Warning - WorkingState is not passing, so not promoted!
 
STKDiscretization::writeSolution: writing time 0.000e+00 with label 1.000e+00 to index 2 in file thermal1D_out.exo
Time = 0.000e+00
         Response[0] = 2.50125542e+02  
 Failure - Stepper failed and can not change time step size!
     Time step type == CONSTANT_STEP_SIZE
 
============================================================================
  Total runtime = 1.36620842e-01 sec = 2.27701403e-03 min
Sat Sep 30 01:08:12 2023
Time integration FAILURE!

T final actual: 0.00000000e+00

p=3: *** Caught standard std::exception of type 'Teuchos::Exceptions::InvalidParameter' :

 /projects/albany/nightlyCDash/build/TrilinosSerialInstall/include/Piro_TempusSolver_Def.hpp:517:
 
 Throw number = 1
 
 Throw test that evaluated to true: true
 
 
  Error! Piro::TempusSolver: time-integrator did not make it to final time specified in Input File.  Final time in input file is 100000, whereas actual final time is 0.  If you'd like to suppress this exception, run with 'Abort on Failure' set to 'false' in Tempus sublist.
 

p=1: *** Caught standard std::exception of type 'Teuchos::Exceptions::InvalidParameter' :

 /projects/albany/nightlyCDash/build/TrilinosSerialInstall/include/Piro_TempusSolver_Def.hpp:517:
 
 Throw number = 1
 
 Throw test that evaluated to true: true
```
I know there were some recent changes to Tempus, but I believe it was just to some of the tests, not to anything fundamental (though tagging @ccober6 who might have more information). 

I think I remember this sort of thing happening in the past, and my solution was to switch from Ifpack2 to MueLu preconditioner...  we need to figure out why the system solves are unconverged.  I suspect it's due to changes to Trilinos since I don't see Albany commits in the past few days that are likely to have caused the problem.

**Comment by ccober6** [comment]
@ikalash Yeah, I do not think any recent Tempus changes are in involved, but @mperego had some recent changes with Piro (#12050) that might be involved.

**Comment by ikalash** [comment]
Thanks @ccober6 .  You are right the culprit was not Tempus. 

I did bisection and the commit that broke things in Trilinos is this one: 

```
commit eebc8109506cd267837b15d2fe342105d74c2460 (HEAD)
Author: Christian Glusa <caglusa@sandia.gov>
Date:   Fri Sep 29 12:42:23 2023 -0600

    MueLu_Amesos2Smoother: Fixes for projection and non-contiguous maps
    
    - Projection was incorrect for nullspaces of dim>1.
    - Check for non-contiguous map was insufficient.
```
by @cgcgcg .  It is causing the issue #988 and I believe #990.  Basically some of our Albany tests that had converged linear solves are now seeing unconverged linear solves.  Tagging @bartgol and @kliegeois who are interested in this for the other two related Albany issues. 

@cgcgcg : would you be willing to work with us to try to get this issue remedied?

**Comment by cgcgcg** [comment]
Of course. I discovered in the meantime that there are some issues with my fix. Do you happen to have the solver setup printout? The bug I was fixing (for a unit test) was in the construction of a direct solver using a non-contiguous map on single rank. However, if the same is run on multiple rank, the matrix is first imported into a contiguous map. The Amesos2 options are a bit confusing in this context.

**Comment by ikalash** [comment]
@cgcgcg : thanks for the prompt reply.  For the Tempus tests, we are just using default MueLu options, if this is what you're asking: https://github.com/sandialabs/Albany/blob/master/tests/demoPDEs/Thermal1D/input.yaml#L113-L116 .  That could be changed if you would like me to test some other  options.  For one of the other tests that got broken, the options can be found here: https://github.com/sandialabs/Albany/blob/master/tests/landIce/SHMIP/input_hewitt.yaml#L197-L207 .  We're not constructing explicitly a direct solver, it is being done in MueLu, my guess is on the coarse grid.  Let me know if this helps.  We can provide you with build scripts for any machine you like pretty much if you want to try to reproduce the problem in Albany.  The tests run very fast.

**Comment by cgcgcg** [comment]
Sorry, what I am asking for is the solver setup output. I think I have a pretty good idea of what went wrong and just want to confirm that. I'll revert the offending change tomorrow.

**Comment by ikalash** [comment]
Sorry, I misunderstood.  I turned on high MueLu output.  The results are in the attached files.  Curiously, the 1 proc version of the problem converges and passes the regression test.

[thermal1D_1proc.txt](https://github.com/sandialabs/Albany/files/12788247/thermal1D_1proc.txt)
[thermal1D_4proc.txt](https://github.com/sandialabs/Albany/files/12788248/thermal1D_4proc.txt)

**Comment by cgcgcg** [comment]
Thanks for the log files. Yep, that sounds exactly right. We can fix this tomorrow.

**Comment by ikalash** [comment]
Sounds great, thanks in advance!  I’m happy to test the pr tomorrow when it’s ready.

**Comment by bartgol** [comment]
@cgcgcg Thanks for the speedy fix!

**Comment by bartgol** [comment]
That seems to work!

**Comment by ikalash** [comment]
https://github.com/trilinos/Trilinos/pull/12356 has fixed this problem.  Thanks again, @cgcgcg!
