### ISSUE TITLE
Compilation errors coming from Omegah in warning-free blake build

### ISSUE THREAD

**Issue by ikalash** [sandialabs/Albany#998]
I turned on Omega_h in the blake nightlies and there are failures in the warning-free one: 

```
[Albany/src/disc/omegah/OmegahPermutation.hpp:103](https://blob/master/Albany/src/disc/omegah/OmegahPermutation.hpp#L103):25: error: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Werror=sign-compare]
```
https://sems-cdash-son.sandia.gov/cdash/viewBuildError.php?buildid=53394

@cwsmith you may be the best one to look at this, but please let me know if I am mistaken.

**Comment by cwsmith** [comment]
@ikalash Taking a look now.  Thank you.

**Comment by cwsmith** [comment]
@ikalash A fix for the `OmegahPermutation.hpp` warnings (there were a few more in my local build) are here https://github.com/sandialabs/Albany/pull/1000.  

I saw a few more warnings (gcc 10 `-Wall`) in some of the other new Omegah source files.  Do you see any others in the dashboard?  I can't access that site.
